/**
 * Types for documentation generation
 */
/** Type of documentation page */
export type DocType = 'api-reference' | 'component' | 'hook' | 'utility' | 'type' | 'changelog' | 'guide';
/** Frontmatter metadata for MDX files */
export interface DocFrontmatter {
    /** Page title */
    title: string;
    /** Meta description */
    description: string;
    /** Category/section */
    category?: string;
    /** Sort order within category */
    order?: number;
    /** Keywords for search */
    keywords?: string[];
    /** Last updated timestamp */
    lastUpdated?: string;
    /** Version when added */
    since?: string;
    /** Deprecation notice */
    deprecated?: string;
    /** Related pages */
    related?: string[];
    /** Auto-generated flag */
    autoGenerated?: boolean;
    /** Source file that generated this */
    generatedFrom?: string;
}
/** A generated documentation file */
export interface GeneratedDoc {
    /** Output file path (relative to docs content dir) */
    path: string;
    /** Generated content (MDX) */
    content: string;
    /** Type of documentation */
    type: DocType;
    /** Frontmatter metadata */
    metadata: DocFrontmatter;
    /** Source files this was generated from */
    sources: string[];
}
/** Documentation update action */
export type DocAction = 'create' | 'update' | 'delete' | 'skip';
/** Planned documentation update */
export interface DocUpdate {
    /** Action to take */
    action: DocAction;
    /** Target file path */
    path: string;
    /** New content (for create/update) */
    content?: string;
    /** Reason for this action */
    reason: string;
    /** Priority of this update */
    priority: 'high' | 'medium' | 'low';
}
/** Documentation generation result */
export interface DocGenerationResult {
    /** Generated documents */
    generated: GeneratedDoc[];
    /** Planned updates */
    updates: DocUpdate[];
    /** Any errors */
    errors: DocGenerationError[];
    /** Statistics */
    stats: {
        created: number;
        updated: number;
        deleted: number;
        skipped: number;
        errors: number;
    };
}
/** Error during doc generation */
export interface DocGenerationError {
    /** Source file */
    source: string;
    /** Target file */
    target?: string;
    /** Error message */
    message: string;
    /** Whether generation can continue */
    recoverable: boolean;
}
/** Template context for component documentation */
export interface ComponentTemplateContext {
    /** Component name */
    name: string;
    /** Component description */
    description: string;
    /** Package name */
    packageName: string;
    /** Import statement */
    importStatement: string;
    /** Props table data */
    props: Array<{
        name: string;
        type: string;
        required: boolean;
        default: string | null;
        description: string;
    }>;
    /** Usage examples */
    examples: string[];
    /** Type signature */
    signature: string;
    /** Related components */
    related: string[];
    /** Version info */
    since?: string;
    /** Deprecation info */
    deprecated?: string;
}
/** Template context for hook documentation */
export interface HookTemplateContext {
    /** Hook name */
    name: string;
    /** Hook description */
    description: string;
    /** Package name */
    packageName: string;
    /** Import statement */
    importStatement: string;
    /** Full signature */
    signature: string;
    /** Parameters */
    parameters: Array<{
        name: string;
        type: string;
        required: boolean;
        description: string;
    }>;
    /** Return type info */
    returns: {
        type: string;
        description: string;
        properties: Array<{
            name: string;
            type: string;
            description: string;
        }>;
    } | null;
    /** Usage examples */
    examples: string[];
    /** Related hooks */
    related: string[];
    /** Version info */
    since?: string;
    /** Deprecation info */
    deprecated?: string;
}
/** Template context for type documentation */
export interface TypeTemplateContext {
    /** Type name */
    name: string;
    /** Type description */
    description: string;
    /** Package name */
    packageName: string;
    /** Import statement */
    importStatement: string;
    /** Full type definition */
    definition: string;
    /** Properties (for interfaces/types) */
    properties: Array<{
        name: string;
        type: string;
        optional: boolean;
        description: string;
    }>;
    /** Related types */
    related: string[];
    /** Version info */
    since?: string;
}
/** Configuration for documentation generator */
export interface DocGeneratorConfig {
    /** Templates directory */
    templatesDir: string;
    /** Output directory for generated docs */
    outputDir: string;
    /** Directory for cached API data */
    apiDataDir: string;
    /** Base URL for links */
    baseUrl: string;
    /** Package name for imports */
    packageName: string;
    /** Whether to include internal APIs */
    includeInternal: boolean;
    /** Dry run mode (don't write files) */
    dryRun: boolean;
}
//# sourceMappingURL=docs.d.ts.map