'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import dynamic from 'next/dynamic';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { ArrowRight, Github, Shield, Sparkles, Zap } from 'lucide-react';
import SplitScreenDemo from '../ui/SplitScreenDemo';
import { durations } from '@/lib/constants';
import { fadeInUp, fadeIn, scaleUp, fadeInRight, reducedMotionConfig, useReducedMotion, } from '@/lib/animations';
// Dynamically import Hero3D to avoid SSR issues with Three.js
const Hero3D = dynamic(() => import('../3d/Hero3D'), {
    ssr: false,
    loading: () => (_jsx("div", { className: "absolute inset-0 flex items-center justify-center", children: _jsx("div", { className: "w-16 h-16 border-4 border-clarity-400/30 border-t-clarity-400 rounded-full animate-spin" }) })),
});
const trustBadges = [
    { icon: Shield, label: 'TypeScript Strict' },
    { icon: Sparkles, label: 'MIT Licensed' },
    { icon: Zap, label: '27KB gzipped' },
];
import MagneticButton from '../ui/MagneticButton';
/**
 * Hero section with benefit-driven headline, animated code preview, and CTAs.
 * Displays only verifiable metrics (component count, bundle size, etc.).
 * Respects reduced-motion preferences via animation library.
 */
export default function HeroSection() {
    return (_jsxs("section", { className: "relative min-h-screen overflow-hidden bg-surface-950", children: [_jsx("div", { className: "absolute inset-0 bg-grid-pattern opacity-30" }), _jsx("div", { className: "absolute inset-0 bg-noise opacity-[0.15] mix-blend-overlay pointer-events-none" }), _jsx("div", { className: "absolute top-1/4 left-1/4 w-96 h-96 bg-clarity-500/20 rounded-full blur-3xl" }), _jsx("div", { className: "absolute bottom-1/4 right-1/4 w-96 h-96 bg-cosmic-500/20 rounded-full blur-3xl" }), _jsx("div", { className: "absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-64 h-64 bg-pink-500/10 rounded-full blur-3xl" }), _jsx("div", { className: "absolute inset-0 opacity-80", children: _jsx(Hero3D, {}) }), _jsxs("div", { className: "relative z-10 mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 pt-32 pb-20", children: [_jsxs("div", { className: "grid lg:grid-cols-2 gap-12 items-center min-h-[calc(100vh-8rem)]", children: [_jsxs(motion.div, { variants: fadeInUp, initial: "hidden", animate: "visible", className: "text-center lg:text-left", children: [_jsx(motion.div, { variants: scaleUp, initial: "hidden", animate: "visible", transition: { delay: 0.1 }, className: "mb-6", children: _jsxs("div", { className: "inline-flex items-center gap-2 px-4 py-2 rounded-full bg-clarity-500/10 border border-clarity-500/20 text-clarity-400 text-sm font-medium", children: [_jsx(Sparkles, { className: "w-4 h-4" }), _jsx("span", { children: "170+ Components \u00B7 MIT Licensed \u00B7 TypeScript Strict" })] }) }), _jsxs(motion.h1, { variants: fadeInUp, initial: "hidden", animate: "visible", transition: { delay: 0.2 }, className: "text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-white mb-6", children: ["Stop Building Chat UI.", ' ', _jsx("span", { className: "gradient-text", children: "Start Shipping AI." })] }), _jsx(motion.p, { variants: fadeInUp, initial: "hidden", animate: "visible", transition: { delay: 0.3 }, className: "text-lg sm:text-xl text-gray-300 mb-8 max-w-xl mx-auto lg:mx-0", children: "170+ production-ready React components for AI chat. OpenAI, Anthropic, and Google AI in one library. Token optimization built in." }), _jsxs(motion.div, { variants: fadeInUp, initial: "hidden", animate: "visible", transition: { delay: 0.4 }, className: "flex flex-col sm:flex-row gap-4 justify-center lg:justify-start mb-10 items-center lg:items-center", children: [_jsx(MagneticButton, { href: "/docs/guides/getting-started", icon: _jsx(ArrowRight, { className: "w-4 h-4" }), children: "Get Started Free" }), _jsx(MagneticButton, { href: "https://github.com/christireid/Clarity-ai-chat-components", variant: "secondary", icon: _jsx(Github, { className: "w-5 h-5" }), children: "View on GitHub" })] }), _jsx(motion.div, { variants: fadeIn, initial: "hidden", animate: "visible", transition: { delay: 0.5 }, className: "flex flex-wrap gap-6 justify-center lg:justify-start", children: trustBadges.map((badge) => {
                                            const Icon = badge.icon;
                                            return (_jsxs("div", { className: "flex items-center gap-2 text-sm text-gray-400", children: [_jsx(Icon, { className: "w-4 h-4 text-clarity-400" }), _jsx("span", { children: badge.label })] }, badge.label));
                                        }) })] }), _jsx(motion.div, { variants: fadeInRight, initial: "hidden", animate: "visible", transition: { delay: 0.3 }, className: "relative w-full lg:w-[120%]", children: _jsx(SplitScreenDemo, {}) })] }), _jsxs(motion.div, { variants: fadeInUp, initial: "hidden", animate: "visible", transition: { delay: 0.6 }, className: "mt-16 lg:mt-0 grid grid-cols-2 sm:grid-cols-4 gap-8 p-8 rounded-2xl glass-card", children: [_jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-3xl sm:text-4xl font-bold text-clarity-400 mb-1", children: "170+" }), _jsx("div", { className: "text-sm text-gray-400", children: "React Components" })] }), _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-3xl sm:text-4xl font-bold text-clarity-400 mb-1", children: "3" }), _jsx("div", { className: "text-sm text-gray-400", children: "AI Providers" })] }), _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-3xl sm:text-4xl font-bold text-clarity-400 mb-1", children: "100%" }), _jsx("div", { className: "text-sm text-gray-400", children: "TypeScript Strict" })] }), _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-3xl sm:text-4xl font-bold text-clarity-400 mb-1", children: "27KB" }), _jsx("div", { className: "text-sm text-gray-400", children: "Gzipped Bundle" })] })] })] }), _jsx(motion.div, { variants: fadeIn, initial: "hidden", animate: "visible", transition: { delay: 1 }, className: "absolute bottom-8 left-1/2 -translate-x-1/2", children: _jsxs("div", { className: "flex flex-col items-center gap-2 text-gray-500", children: [_jsx("span", { className: "text-xs uppercase tracking-widest", children: "Scroll" }), _jsx(motion.div, { animate: { y: [0, 8, 0] }, transition: { duration: durations.slower, repeat: Infinity }, className: "w-6 h-10 rounded-full border-2 border-gray-600 flex items-start justify-center p-1", children: _jsx("div", { className: "w-1.5 h-3 rounded-full bg-gray-500" }) })] }) })] }));
}
//# sourceMappingURL=HeroSection.js.map