import type { Meta, StoryObj } from '@storybook/react';
import { Message } from '../../../packages/react/src/components/message';
declare const meta: Meta<typeof Message>;
export default meta;
type Story = StoryObj<typeof Message>;
export declare const UserMessage: Story;
export declare const AssistantMessage: Story;
export declare const StreamingMessage: Story;
export declare const SlideInAnimation: Story;
export declare const AvatarBounce: Story;
export declare const ActionBarReveal: Story;
export declare const FeedbackWithConfetti: Story;
export declare const StreamingCursor: Story;
export declare const WithMarkdown: Story;
export declare const WithCodeBlock: Story;
export declare const WithAttachments: Story;
export declare const SendingStatus: Story;
export declare const ErrorStatus: Story;
export declare const WithMetadata: Story;
export declare const Conversation: Story;
export declare const InteractiveDemo: Story;
//# sourceMappingURL=Message.stories.d.ts.map