import type { Meta, StoryObj } from '@storybook/react';
import { ModelSelector } from '@clarity-chat/react';
declare const meta: Meta<typeof ModelSelector>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const OpenAIModels: Story;
export declare const AnthropicModels: Story;
export declare const GoogleModels: Story;
export declare const WithoutMetrics: Story;
export declare const WithoutDescriptions: Story;
export declare const Disabled: Story;
export declare const MinimalUI: Story;
export declare const InteractiveWithDetails: Story;
export declare const ComparisonTool: Story;
export declare const SingleModel: Story;
export declare const LongModelNames: Story;
export declare const ManyModels: Story;
export declare const NoModelSelected: Story;
//# sourceMappingURL=ModelSelector.stories.d.ts.map