'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line, PieChart, Pie, Cell } from 'recharts';
import { BarChart3, Trash2 } from 'lucide-react';
import { motion } from 'framer-motion';
export function ChartGallery({ charts }) {
    if (charts.length === 0) {
        return (_jsxs("div", { className: "text-center py-12 text-gray-500 dark:text-gray-400", children: [_jsx(BarChart3, { className: "w-12 h-12 mx-auto mb-3 opacity-50" }), _jsx("p", { className: "text-sm", children: "No charts generated yet" }), _jsx("p", { className: "text-xs mt-1", children: "Ask a question to create your first chart" })] }));
    }
    return (_jsx("div", { className: "space-y-4", children: charts.map((chart, idx) => (_jsxs(motion.div, { initial: { opacity: 0, scale: 0.95 }, animate: { opacity: 1, scale: 1 }, transition: { delay: idx * 0.1 }, className: "bg-white dark:bg-gray-800 rounded-lg p-4 border border-gray-200 dark:border-gray-700 shadow-sm", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsx("h4", { className: "font-semibold text-sm", children: chart.title }), _jsx("button", { className: "text-gray-400 hover:text-red-500 transition-colors", children: _jsx(Trash2, { className: "w-4 h-4" }) })] }), _jsxs("div", { className: "h-48", children: [chart.chartType === 'bar' && (_jsx(ResponsiveContainer, { width: "100%", height: "100%", children: _jsxs(BarChart, { data: chart.data, children: [_jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: "#e5e7eb" }), _jsx(XAxis, { dataKey: "region", stroke: "#6b7280" }), _jsx(YAxis, { stroke: "#6b7280" }), _jsx(Tooltip, {}), _jsx(Bar, { dataKey: "sales", fill: "#6366f1" })] }) })), chart.chartType === 'line' && (_jsx(ResponsiveContainer, { width: "100%", height: "100%", children: _jsxs(LineChart, { data: chart.data, children: [_jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: "#e5e7eb" }), _jsx(XAxis, { dataKey: "date", stroke: "#6b7280" }), _jsx(YAxis, { stroke: "#6b7280" }), _jsx(Tooltip, {}), _jsx(Line, { type: "monotone", dataKey: "value", stroke: "#6366f1", strokeWidth: 2 })] }) })), chart.chartType === 'pie' && (_jsx(ResponsiveContainer, { width: "100%", height: "100%", children: _jsxs(PieChart, { children: [_jsx(Pie, { data: chart.data, cx: "50%", cy: "50%", labelLine: false, label: ({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`, outerRadius: 60, fill: "#8884d8", dataKey: "value", children: chart.data.map((entry, index) => (_jsx(Cell, { fill: ['#6366f1', '#8b5cf6', '#ec4899', '#f59e0b'][index % 4] }, `cell-${index}`))) }), _jsx(Tooltip, {})] }) }))] })] }, idx))) }));
}
//# sourceMappingURL=ChartGallery.js.map