#!/bin/bash

# GitHub Packages Setup Script for Clarity Chat
# This script helps you configure GitHub Packages authentication

set -e

echo "🚀 GitHub Packages Setup for Clarity Chat"
echo "=========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if .npmrc already exists
if [ -f .npmrc ]; then
    echo -e "${YELLOW}⚠️  .npmrc already exists!${NC}"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${RED}❌ Setup cancelled${NC}"
        exit 1
    fi
fi

# Check if GITHUB_TOKEN environment variable exists
if [ -n "$GITHUB_TOKEN" ]; then
    echo -e "${GREEN}✅ Found GITHUB_TOKEN environment variable${NC}"
    read -p "Use this token for .npmrc? (Y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        TOKEN=$GITHUB_TOKEN
        echo -e "${GREEN}✅ Using GITHUB_TOKEN from environment${NC}"
    fi
fi

# If no token from environment, ask user to provide one
if [ -z "$TOKEN" ]; then
    echo ""
    echo -e "${BLUE}📝 You need a GitHub Personal Access Token${NC}"
    echo -e "${BLUE}   Generate one at: https://github.com/settings/tokens${NC}"
    echo -e "${BLUE}   Required scopes: read:packages, write:packages, repo${NC}"
    echo ""
    read -p "Enter your GitHub Personal Access Token: " -s TOKEN
    echo
    
    if [ -z "$TOKEN" ]; then
        echo -e "${RED}❌ No token provided. Setup cancelled.${NC}"
        exit 1
    fi
fi

# Validate token format (should start with ghp_ or github_pat_)
if [[ ! $TOKEN =~ ^(ghp_|github_pat_) ]]; then
    echo -e "${YELLOW}⚠️  Warning: Token doesn't match expected format${NC}"
    read -p "Continue anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${RED}❌ Setup cancelled${NC}"
        exit 1
    fi
fi

# Create .npmrc file
echo -e "${BLUE}📝 Creating .npmrc file...${NC}"
cat > .npmrc << EOF
# GitHub Packages Configuration
# Auto-generated by setup-github-packages.sh

# Point @clarity-chat scoped packages to GitHub Packages
@clarity-chat:registry=https://npm.pkg.github.com

# Authentication token
//npm.pkg.github.com/:_authToken=$TOKEN
EOF

echo -e "${GREEN}✅ .npmrc created successfully${NC}"

# Ensure .npmrc is in .gitignore
if [ -f .gitignore ]; then
    if ! grep -q "^\.npmrc$" .gitignore; then
        echo -e "${BLUE}📝 Adding .npmrc to .gitignore...${NC}"
        echo ".npmrc" >> .gitignore
        echo -e "${GREEN}✅ .npmrc added to .gitignore${NC}"
    else
        echo -e "${GREEN}✅ .npmrc already in .gitignore${NC}"
    fi
else
    echo -e "${YELLOW}⚠️  No .gitignore found. Creating one...${NC}"
    echo ".npmrc" > .gitignore
    echo -e "${GREEN}✅ .gitignore created with .npmrc${NC}"
fi

# Test authentication
echo ""
echo -e "${BLUE}🔍 Testing authentication...${NC}"
if npm whoami --registry=https://npm.pkg.github.com 2>/dev/null; then
    echo -e "${GREEN}✅ Authentication successful!${NC}"
    USERNAME=$(npm whoami --registry=https://npm.pkg.github.com)
    echo -e "${GREEN}   Logged in as: $USERNAME${NC}"
else
    echo -e "${YELLOW}⚠️  Could not verify authentication${NC}"
    echo -e "${YELLOW}   This might be normal if you haven't published packages yet${NC}"
fi

echo ""
echo -e "${GREEN}🎉 Setup Complete!${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo -e "  1. Install packages: ${GREEN}npm install${NC}"
echo -e "  2. Build packages:   ${GREEN}npm run build${NC}"
echo -e "  3. Publish packages: ${GREEN}npm run release${NC}"
echo ""
echo -e "${BLUE}To install a package from GitHub Packages:${NC}"
echo -e "  ${GREEN}npm install @clarity-chat/react${NC}"
echo ""
echo -e "${YELLOW}⚠️  Remember: Never commit .npmrc with your token!${NC}"
