'use client'

import { useState, useRef } from 'react'
import { PageHeader, ComponentSection } from '@/components/component-section'
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  Button,
  Badge,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  ScrollArea,
  cn,
} from '@clarity-chat/primitives'
import {
  Send,
  Mic,
  MicOff,
  Paperclip,
  Image,
  File,
  X,
  AtSign,
  Hash,
  Smile,
  Code,
  Bold,
  Italic,
  List,
  Link,
  ChevronDown,
  Sparkles,
  Wand2,
  Volume2,
  VolumeX,
  Settings,
  Keyboard,
  Search,
  Package,
  HelpCircle,
  Trash2,
  Download,
  BarChart,
  FileText,
  Zap,
  Terminal,
} from 'lucide-react'

// Types defined locally for the showcase to avoid deep import resolution issues
// with @clarity-chat/react/internal (no .d.ts files generated by tsup)
interface SlashCommand {
  name: string
  description: string
  icon: React.ComponentType<{ className?: string }>
  category: string
  onSelect: () => void
  available?: boolean
}

interface SavedPrompt {
  id: string
  name: string
  description?: string
  content: string
}

interface MessageAttachment {
  id: string
  name: string
  size: number
  type: string
  url?: string
  mimeType?: string
}

interface InputSuggestion {
  id: string
  type: 'prompt' | 'command' | 'mention'
  label: string
  description?: string
  value: string
}

// Simplified AdvancedChatInput for showcase - demonstrates the same features
// as the full @clarity-chat/react/internal AdvancedChatInput component
function AdvancedChatInput({
  value,
  onChange,
  onSubmit,
  onSuggestionRequest,
  savedPrompts = [],
  placeholder = 'Type a message... Use @ for prompts, / for commands',
  maxLength,
}: {
  value: string
  onChange: (value: string) => void
  onSubmit: (value: string, attachments?: MessageAttachment[]) => void
  onSuggestionRequest?: (query: string, trigger: '@' | '/') => Promise<InputSuggestion[]>
  savedPrompts?: SavedPrompt[]
  placeholder?: string
  maxLength?: number
}) {
  const [suggestions, setSuggestions] = useState<InputSuggestion[]>([])
  const [selectedIndex, setSelectedIndex] = useState(0)
  const [showSuggestions, setShowSuggestions] = useState(false)
  const [triggerChar, setTriggerChar] = useState<'@' | '/' | null>(null)
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const newValue = e.target.value
    onChange(newValue)

    const cursorPos = e.target.selectionStart || 0
    const beforeCursor = newValue.slice(0, cursorPos)
    const lastAtIndex = beforeCursor.lastIndexOf('@')
    const lastSlashIndex = beforeCursor.lastIndexOf('/')
    const lastSpaceIndex = beforeCursor.lastIndexOf(' ')

    if (lastAtIndex > lastSpaceIndex) {
      const query = beforeCursor.slice(lastAtIndex + 1)
      setTriggerChar('@')
      setShowSuggestions(true)
      if (onSuggestionRequest) {
        onSuggestionRequest(query, '@').then((results) => {
          setSuggestions(results)
          setSelectedIndex(0)
        })
      }
    } else if (lastSlashIndex > lastSpaceIndex) {
      const query = beforeCursor.slice(lastSlashIndex + 1)
      setTriggerChar('/')
      setShowSuggestions(true)
      if (onSuggestionRequest) {
        onSuggestionRequest(query, '/').then((results) => {
          setSuggestions(results)
          setSelectedIndex(0)
        })
      }
    } else {
      setShowSuggestions(false)
      setTriggerChar(null)
    }
  }

  const selectSuggestion = (suggestion: InputSuggestion) => {
    const cursorPos = textareaRef.current?.selectionStart || 0
    const beforeCursor = value.slice(0, cursorPos)
    const afterCursor = value.slice(cursorPos)
    const triggerIndex = triggerChar === '@'
      ? beforeCursor.lastIndexOf('@')
      : beforeCursor.lastIndexOf('/')
    const newValue = beforeCursor.slice(0, triggerIndex) + suggestion.value + ' ' + afterCursor
    onChange(newValue)
    setShowSuggestions(false)
    setTriggerChar(null)
    setTimeout(() => textareaRef.current?.focus(), 0)
  }

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (showSuggestions && suggestions.length > 0) {
      if (e.key === 'ArrowDown') {
        e.preventDefault()
        setSelectedIndex((prev) => (prev + 1) % suggestions.length)
      } else if (e.key === 'ArrowUp') {
        e.preventDefault()
        setSelectedIndex((prev) => (prev - 1 + suggestions.length) % suggestions.length)
      } else if (e.key === 'Tab' || e.key === 'Enter') {
        e.preventDefault()
        const selected = suggestions[selectedIndex]
        if (selected) selectSuggestion(selected)
        return
      } else if (e.key === 'Escape') {
        e.preventDefault()
        setShowSuggestions(false)
        return
      }
    }
    if (e.key === 'Enter' && !e.shiftKey && !showSuggestions) {
      e.preventDefault()
      if (value.trim()) {
        onSubmit(value)
        onChange('')
      }
    }
  }

  const charCount = value.length
  const isOverLimit = maxLength ? charCount > maxLength : false

  return (
    <div className="relative border rounded-lg bg-background">
      {/* Suggestions Dropdown */}
      {showSuggestions && suggestions.length > 0 && (
        <div
          className="absolute bottom-full left-0 right-0 mb-2 bg-popover border rounded-lg shadow-lg max-h-64 overflow-y-auto z-50"
          role="listbox"
          aria-label="Suggestions"
        >
          {suggestions.map((suggestion, index) => (
            <button
              key={suggestion.id}
              onClick={() => selectSuggestion(suggestion)}
              className={cn(
                'w-full text-left px-4 py-2 hover:bg-accent transition-colors',
                index === selectedIndex && 'bg-accent'
              )}
              aria-selected={index === selectedIndex}
              role="option"
            >
              <div className="flex items-center gap-2">
                <div className="flex-1 min-w-0">
                  <p className="font-medium text-sm">{suggestion.label}</p>
                  {suggestion.description && (
                    <p className="text-xs text-muted-foreground truncate">
                      {suggestion.description}
                    </p>
                  )}
                </div>
                <Badge variant="secondary" className="text-xs">
                  {triggerChar}{suggestion.label}
                </Badge>
              </div>
            </button>
          ))}
          <div className="px-4 py-2 text-xs text-muted-foreground border-t bg-muted/50">
            <kbd className="px-1.5 py-0.5 text-xs border rounded">Tab</kbd> or{' '}
            <kbd className="px-1.5 py-0.5 text-xs border rounded">Enter</kbd> to select
          </div>
        </div>
      )}

      {/* Input Area */}
      <div className="flex gap-2 p-3">
        <Button
          type="button"
          variant="ghost"
          size="icon"
          title="Attach files"
          aria-label="Attach files"
        >
          <Paperclip className="h-4 w-4" />
        </Button>
        <div className="flex-1 relative">
          <textarea
            ref={textareaRef}
            value={value}
            onChange={handleChange}
            onKeyDown={handleKeyDown}
            placeholder={placeholder}
            maxLength={maxLength}
            rows={1}
            className={cn(
              'w-full resize-none bg-transparent text-sm outline-none py-2',
              isOverLimit && 'text-destructive'
            )}
          />
          {maxLength && (
            <div className={cn(
              'absolute bottom-0 right-0 text-xs',
              isOverLimit ? 'text-destructive' : 'text-muted-foreground'
            )}>
              {charCount}/{maxLength}
            </div>
          )}
        </div>
        <Button
          onClick={() => {
            if (value.trim()) {
              onSubmit(value)
              onChange('')
            }
          }}
          disabled={!value.trim() || isOverLimit}
          size="icon"
          title="Send message (Enter)"
          aria-label="Send message"
        >
          <Send className="h-4 w-4" />
        </Button>
      </div>
    </div>
  )
}

// Simple SlashCommandMenu component for showcase
function SlashCommandMenu({
  commands,
  isOpen,
  query,
  onSelect,
  onClose,
  position = 'below',
}: {
  commands: SlashCommand[]
  isOpen: boolean
  query: string
  onSelect: (command: SlashCommand) => void
  onClose: () => void
  position?: 'above' | 'below'
}) {
  if (!isOpen) return null

  // Filter commands based on query
  const filteredCommands = commands.filter(
    (cmd) =>
      cmd.name.toLowerCase().includes(query.toLowerCase()) ||
      cmd.description.toLowerCase().includes(query.toLowerCase())
  )

  if (filteredCommands.length === 0) return null

  return (
    <div
      className={cn(
        'absolute left-0 right-0 z-50 mt-2',
        'bg-popover border rounded-lg shadow-lg',
        'max-h-[300px] overflow-auto',
        position === 'above' && 'bottom-full mb-2'
      )}
    >
      <div className="p-2 space-y-1">
        {filteredCommands.map((cmd) => (
          <button
            key={cmd.name}
            onClick={() => onSelect(cmd)}
            className={cn(
              'w-full flex items-center gap-3 px-3 py-2',
              'rounded-md hover:bg-accent',
              'text-left transition-colors',
              cmd.available === false && 'opacity-50 cursor-not-allowed'
            )}
            disabled={cmd.available === false}
          >
            <cmd.icon className="h-4 w-4 shrink-0" />
            <div className="flex-1 min-w-0">
              <div className="text-sm font-medium">{cmd.name}</div>
              <div className="text-xs text-muted-foreground truncate">
                {cmd.description}
              </div>
            </div>
            <Badge variant="secondary" className="text-xs">
              {cmd.category}
            </Badge>
          </button>
        ))}
      </div>
    </div>
  )
}

// ============================================================================
// SLASH COMMANDS DEMO
// ============================================================================
function SlashCommandsDemo() {
  const [inputValue, setInputValue] = useState('')
  const [isOpen, setIsOpen] = useState(false)
  const [cursorPosition, setCursorPosition] = useState(0)
  const inputRef = useRef<HTMLInputElement>(null)

  // Define available slash commands
  const commands: SlashCommand[] = [
    {
      name: '/help',
      description: 'Show available commands and documentation',
      icon: HelpCircle,
      category: 'General',
      onSelect: () => console.log('Show help'),
    },
    {
      name: '/clear',
      description: 'Clear the current conversation',
      icon: Trash2,
      category: 'General',
      onSelect: () => console.log('Clear conversation'),
    },
    {
      name: '/export',
      description: 'Export conversation as JSON or Markdown',
      icon: Download,
      category: 'General',
      onSelect: () => console.log('Export conversation'),
    },
    {
      name: '/search',
      description: 'Search through conversation history',
      icon: Search,
      category: 'Tools',
      onSelect: () => console.log('Open search'),
    },
    {
      name: '/model',
      description: 'Switch AI model (GPT-4, Claude, etc.)',
      icon: Sparkles,
      category: 'AI',
      onSelect: () => console.log('Switch model'),
    },
    {
      name: '/bundle',
      description: 'Analyze bundle size and dependencies',
      icon: Package,
      category: 'Tools',
      onSelect: () => console.log('Analyze bundle'),
    },
    {
      name: '/code',
      description: 'Generate code example in specified language',
      icon: Code,
      category: 'AI',
      onSelect: () => console.log('Generate code'),
    },
    {
      name: '/stats',
      description: 'Show conversation statistics and metrics',
      icon: BarChart,
      category: 'Tools',
      onSelect: () => console.log('Show stats'),
    },
    {
      name: '/prompt',
      description: 'Load a saved prompt template',
      icon: FileText,
      category: 'AI',
      onSelect: () => console.log('Load prompt'),
    },
    {
      name: '/terminal',
      description: 'Execute terminal command (dev mode)',
      icon: Terminal,
      category: 'Tools',
      available: false, // Example of disabled command
      onSelect: () => console.log('Execute terminal'),
    },
  ]

  // Handle input change
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value
    setInputValue(value)
    setCursorPosition(e.target.selectionStart || 0)

    // Check if slash command triggered
    const beforeCursor = value.slice(0, e.target.selectionStart || 0)
    const lastSlashIndex = beforeCursor.lastIndexOf('/')
    const lastSpaceIndex = beforeCursor.lastIndexOf(' ')

    // Show menu if "/" is after last space
    if (lastSlashIndex > lastSpaceIndex) {
      setIsOpen(true)
    } else {
      setIsOpen(false)
    }
  }

  // Handle command selection
  const handleCommandSelect = (command: SlashCommand) => {
    // Replace the slash command text with the selected command
    const beforeCursor = inputValue.slice(0, cursorPosition)
    const afterCursor = inputValue.slice(cursorPosition)
    const lastSlashIndex = beforeCursor.lastIndexOf('/')

    const newValue =
      beforeCursor.slice(0, lastSlashIndex) + command.name + ' ' + afterCursor

    setInputValue(newValue)
    setIsOpen(false)

    // Refocus input
    setTimeout(() => {
      inputRef.current?.focus()
      const newCursorPos = lastSlashIndex + command.name.length + 1
      inputRef.current?.setSelectionRange(newCursorPos, newCursorPos)
    }, 0)

    // Execute command
    command.onSelect()
  }

  // Get query for filtering
  const getQuery = () => {
    const beforeCursor = inputValue.slice(0, cursorPosition)
    const lastSlashIndex = beforeCursor.lastIndexOf('/')
    if (lastSlashIndex === -1) return ''
    return beforeCursor.slice(lastSlashIndex + 1)
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-lg">Slash Commands</CardTitle>
        <CardDescription>
          Type "/" to see available commands with full keyboard navigation
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          <div className="relative">
            <input
              ref={inputRef}
              type="text"
              value={inputValue}
              onChange={handleChange}
              placeholder="Type / to see commands..."
              className="w-full px-4 py-3 border rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
            />

            {/* Slash Command Menu */}
            <SlashCommandMenu
              commands={commands}
              isOpen={isOpen}
              query={getQuery()}
              onSelect={handleCommandSelect}
              onClose={() => setIsOpen(false)}
              position="below"
            />
          </div>

          {/* Features List */}
          <div className="grid grid-cols-2 gap-3 text-xs">
            <div className="flex items-center gap-2 text-muted-foreground">
              <Zap className="h-3 w-3 text-primary" />
              <span>10 built-in commands</span>
            </div>
            <div className="flex items-center gap-2 text-muted-foreground">
              <Keyboard className="h-3 w-3 text-primary" />
              <span>Full keyboard navigation</span>
            </div>
            <div className="flex items-center gap-2 text-muted-foreground">
              <Search className="h-3 w-3 text-primary" />
              <span>Fuzzy search filtering</span>
            </div>
            <div className="flex items-center gap-2 text-muted-foreground">
              <Package className="h-3 w-3 text-primary" />
              <span>Categorized commands</span>
            </div>
          </div>

          {/* Keyboard Shortcuts */}
          <div className="p-3 bg-muted/50 rounded-lg space-y-2">
            <p className="text-xs font-medium">Keyboard Shortcuts:</p>
            <div className="grid grid-cols-2 gap-2 text-xs text-muted-foreground">
              <span>
                <kbd className="px-1.5 py-0.5 bg-background border rounded">
                  ↑↓
                </kbd>{' '}
                Navigate
              </span>
              <span>
                <kbd className="px-1.5 py-0.5 bg-background border rounded">
                  Tab
                </kbd>{' '}
                Cycle
              </span>
              <span>
                <kbd className="px-1.5 py-0.5 bg-background border rounded">
                  Enter
                </kbd>{' '}
                Select
              </span>
              <span>
                <kbd className="px-1.5 py-0.5 bg-background border rounded">
                  Esc
                </kbd>{' '}
                Close
              </span>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

// ============================================================================
// MENTIONS DEMO (Simplified for showcase)
// ============================================================================
function MentionsComponentDemo() {
  const [message, setMessage] = useState('')
  const [showMentions, setShowMentions] = useState(false)
  const [selectedUsers, setSelectedUsers] = useState<string[]>([])

  // Sample users
  const users = [
    { id: '1', name: 'Alice Johnson', role: 'Developer', isOnline: true },
    { id: '2', name: 'Bob Smith', role: 'Designer', isOnline: true },
    { id: '3', name: 'Carol Williams', role: 'Product Manager', isOnline: false },
    { id: '4', name: 'David Brown', role: 'Engineer', isOnline: true },
    { id: '5', name: 'Eve Davis', role: 'Marketing', isOnline: false },
  ]

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value
    setMessage(value)

    // Show mentions dropdown when @ is typed
    const lastAtIndex = value.lastIndexOf('@')
    const lastSpaceIndex = value.lastIndexOf(' ')
    setShowMentions(lastAtIndex > lastSpaceIndex && lastAtIndex !== -1)
  }

  const handleUserSelect = (user: typeof users[0]) => {
    // Add user to message
    const lastAtIndex = message.lastIndexOf('@')
    const newMessage = message.slice(0, lastAtIndex) + `@${user.name} `
    setMessage(newMessage)
    setShowMentions(false)
    setSelectedUsers([...selectedUsers, user.id])
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-lg">Mention System</CardTitle>
        <CardDescription>
          Real @mention autocomplete with fuzzy search and keyboard navigation
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {/* Simplified Mention Input */}
          <div className="relative">
            <input
              type="text"
              value={message}
              onChange={handleInputChange}
              placeholder="Type @ to mention someone..."
              className="w-full px-4 py-3 border rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
            />

            {/* Mentions dropdown */}
            {showMentions && (
              <div className="absolute left-0 right-0 top-full mt-2 z-50 bg-popover border rounded-lg shadow-lg max-h-[200px] overflow-auto">
                <div className="p-2 space-y-1">
                  {users.map((user) => (
                    <button
                      key={user.id}
                      onClick={() => handleUserSelect(user)}
                      className="w-full flex items-center gap-3 px-3 py-2 rounded-md hover:bg-accent text-left"
                    >
                      <div className={cn(
                        'w-2 h-2 rounded-full',
                        user.isOnline ? 'bg-green-500' : 'bg-gray-400'
                      )} />
                      <div className="flex-1">
                        <div className="text-sm font-medium">{user.name}</div>
                        <div className="text-xs text-muted-foreground">{user.role}</div>
                      </div>
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Mentioned Users Display */}
          {selectedUsers.length > 0 && (
            <div className="space-y-2">
              <p className="text-xs font-medium text-muted-foreground">
                Mentioned Users:
              </p>
              <div className="flex flex-wrap gap-2">
                {selectedUsers.map((userId) => {
                  const user = users.find((u) => u.id === userId)
                  if (!user) return null
                  return (
                    <Badge key={userId} variant="secondary" className="gap-1">
                      <AtSign className="h-3 w-3" />
                      {user.name}
                    </Badge>
                  )
                })}
              </div>
            </div>
          )}

          {/* Features List */}
          <div className="p-3 bg-muted/50 rounded-lg space-y-2">
            <p className="text-xs font-medium">Features:</p>
            <ul className="text-xs text-muted-foreground space-y-1">
              <li>• Fuzzy search matching</li>
              <li>• Keyboard navigation (↑↓ Tab Enter)</li>
              <li>• Online status indicators</li>
              <li>• Role display</li>
              <li>• Automatic mention extraction</li>
            </ul>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

// ============================================================================
// ADVANCED CHAT INPUT DEMO (Combined slash + mentions)
// ============================================================================
function AdvancedInputDemo() {
  const [message, setMessage] = useState('')
  const [attachments, setAttachments] = useState<MessageAttachment[]>([])

  // Sample saved prompts
  const savedPrompts: SavedPrompt[] = [
    {
      id: '1',
      name: 'explain-concept',
      description: 'Explain a programming concept',
      content: 'Explain [concept] with practical examples and use cases',
    },
    {
      id: '2',
      name: 'code-review',
      description: 'Request code review',
      content: 'Review this code for best practices and potential issues',
    },
    {
      id: '3',
      name: 'debug-help',
      description: 'Debug assistance',
      content: 'Help me debug this issue: [description]',
    },
  ]

  // Handle submission
  const handleSubmit = (value: string, attachments?: MessageAttachment[]) => {
    console.log('Submit:', { value, attachments })
    setMessage('')
    setAttachments([])
  }

  // Custom suggestion request (async simulation)
  const handleSuggestionRequest = async (
    query: string,
    trigger: '@' | '/'
  ) => {
    // Simulate async loading
    await new Promise((resolve) => setTimeout(resolve, 100))

    if (trigger === '@') {
      // Return filtered prompts
      return savedPrompts
        .filter((p) => p.name.includes(query.toLowerCase()))
        .map((p) => ({
          id: p.id,
          type: 'prompt' as const,
          label: p.name,
          description: p.description,
          value: p.content,
        }))
    }

    // Return slash commands
    const commands = [
      {
        id: '1',
        type: 'command' as const,
        label: 'help',
        description: 'Show help',
        value: '/help',
      },
      {
        id: '2',
        type: 'command' as const,
        label: 'clear',
        description: 'Clear chat',
        value: '/clear',
      },
      {
        id: '3',
        type: 'command' as const,
        label: 'export',
        description: 'Export conversation',
        value: '/export',
      },
    ]

    return commands.filter((c) => c.label.includes(query.toLowerCase()))
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-lg">Advanced Chat Input</CardTitle>
        <CardDescription>
          Combined input with slash commands, @mentions, and file attachments
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {/* Actual AdvancedChatInput Component */}
          <AdvancedChatInput
            value={message}
            onChange={setMessage}
            onSubmit={handleSubmit}
            onSuggestionRequest={handleSuggestionRequest}
            // savedPrompts={savedPrompts} // TODO: Fix type inference issue with internal exports
            placeholder="Type @ for prompts, / for commands..."
            maxLength={4000}
          />

          {/* Features List */}
          <div className="p-3 bg-muted/50 rounded-lg">
            <p className="text-xs font-medium mb-2">Combined Features:</p>
            <div className="grid grid-cols-2 gap-2 text-xs text-muted-foreground">
              <div className="flex items-center gap-2">
                <span className="text-primary">@</span>
                <span>Saved prompts</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-primary">/</span>
                <span>Commands</span>
              </div>
              <div className="flex items-center gap-2">
                <Paperclip className="h-3 w-3 text-primary" />
                <span>File upload</span>
              </div>
              <div className="flex items-center gap-2">
                <Keyboard className="h-3 w-3 text-primary" />
                <span>Keyboard nav</span>
              </div>
            </div>
          </div>

          {/* Usage Example */}
          <div className="p-3 bg-primary/5 border border-primary/20 rounded-lg">
            <p className="text-xs font-medium mb-2">Try it:</p>
            <ul className="text-xs text-muted-foreground space-y-1">
              <li>1. Type "/" to see available commands</li>
              <li>2. Type "@" to see saved prompts</li>
              <li>3. Use ↑↓ arrows or Tab to navigate</li>
              <li>4. Press Enter to select</li>
              <li>5. Attach files with the paperclip button</li>
            </ul>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

// ============================================================================
// AI TEXTAREA DEMO
// ============================================================================
function AITextareaDemo() {
  const [value, setValue] = useState('')
  const [showSuggestion, setShowSuggestion] = useState(false)
  const suggestion = 'explain how React hooks work with practical examples'

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-lg">AI Textarea</CardTitle>
        <CardDescription>
          Textarea with AI-powered autocomplete suggestions
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          <div className="relative">
            <div className="border rounded-lg overflow-hidden">
              <div className="relative">
                <textarea
                  value={value}
                  onChange={(e) => {
                    setValue(e.target.value)
                    setShowSuggestion(e.target.value.length > 5)
                  }}
                  placeholder="Start typing to see AI suggestions..."
                  className="w-full min-h-[100px] p-3 text-sm outline-none resize-none"
                  rows={4}
                />
                {showSuggestion && value && (
                  <div className="absolute inset-0 pointer-events-none p-3">
                    <span className="text-sm text-transparent">{value}</span>
                    <span className="text-sm text-muted-foreground/50">
                      {suggestion}
                    </span>
                  </div>
                )}
              </div>
              <div className="flex items-center justify-between p-2 border-t bg-muted/30">
                <div className="flex items-center gap-2">
                  <Badge variant="secondary" className="text-xs gap-1">
                    <Sparkles className="h-3 w-3" />
                    AI Suggestions
                  </Badge>
                  <span className="text-xs text-muted-foreground">
                    Press{' '}
                    <kbd className="px-1 py-0.5 bg-muted rounded text-xs">
                      Tab
                    </kbd>{' '}
                    to accept
                  </span>
                </div>
                <span className="text-xs text-muted-foreground">
                  {value.length}/4000
                </span>
              </div>
            </div>
          </div>

          <div className="text-xs text-muted-foreground">
            <p className="flex items-center gap-2">
              <Wand2 className="h-3 w-3" />
              Type a few words and AI will suggest completions based on context
            </p>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

// ============================================================================
// VOICE INPUT DEMO
// ============================================================================
function VoiceInputDemo() {
  const [isRecording, setIsRecording] = useState(false)
  const [transcript, setTranscript] = useState('')

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-lg">Voice Input</CardTitle>
        <CardDescription>
          Speech-to-text input with visual feedback
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-6">
          {/* Recording Button */}
          <div className="flex items-center justify-center">
            <button
              onClick={() => setIsRecording(!isRecording)}
              className={cn(
                'relative w-20 h-20 rounded-full flex items-center justify-center transition-all',
                isRecording
                  ? 'bg-red-500 text-white'
                  : 'bg-primary text-primary-foreground hover:bg-primary/90'
              )}
            >
              {isRecording ? (
                <>
                  <MicOff className="h-8 w-8" />
                  <span className="absolute inset-0 rounded-full animate-ping bg-red-500/30" />
                </>
              ) : (
                <Mic className="h-8 w-8" />
              )}
            </button>
          </div>

          {/* Status */}
          <div className="text-center">
            {isRecording ? (
              <div className="space-y-2">
                <p className="text-sm font-medium text-red-500">Recording...</p>
                <div className="flex items-center justify-center gap-1">
                  {[...Array(5)].map((_, i) => (
                    <div
                      key={i}
                      className="w-1 bg-red-500 rounded-full animate-pulse"
                      style={{
                        height: `${20 + Math.random() * 20}px`,
                        animationDelay: `${i * 100}ms`,
                      }}
                    />
                  ))}
                </div>
              </div>
            ) : (
              <p className="text-sm text-muted-foreground">
                Click the microphone to start recording
              </p>
            )}
          </div>

          {/* Transcript */}
          {transcript && (
            <div className="p-3 bg-muted rounded-lg">
              <p className="text-xs text-muted-foreground mb-1">Transcript:</p>
              <p className="text-sm">{transcript}</p>
            </div>
          )}

          {/* Voice Settings */}
          <div className="flex items-center justify-center gap-4">
            <Button variant="outline" size="sm" className="gap-2">
              <Volume2 className="h-4 w-4" />
              Test Audio
            </Button>
            <Button variant="outline" size="sm" className="gap-2">
              <Settings className="h-4 w-4" />
              Settings
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

// ============================================================================
// KEYBOARD SHORTCUTS DEMO
// ============================================================================
function KeyboardShortcutsDemo() {
  const shortcuts = [
    { keys: ['⌘', 'Enter'], action: 'Send message' },
    { keys: ['⌘', 'K'], action: 'Open command palette' },
    { keys: ['⌘', '/'], action: 'Show keyboard shortcuts' },
    { keys: ['⌘', 'B'], action: 'Bold text' },
    { keys: ['⌘', 'I'], action: 'Italic text' },
    { keys: ['Esc'], action: 'Cancel / Close' },
    { keys: ['Tab'], action: 'Accept suggestion' },
    { keys: ['↑', '↑'], action: 'Edit last message' },
    { keys: ['↑'], action: 'Navigate up' },
    { keys: ['↓'], action: 'Navigate down' },
    { keys: ['Enter'], action: 'Select / Confirm' },
    { keys: ['/', '...'], action: 'Trigger slash commands' },
    { keys: ['@', '...'], action: 'Trigger mentions' },
  ]

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-lg">Keyboard Shortcuts</CardTitle>
        <CardDescription>Quick actions for power users</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="grid md:grid-cols-2 gap-3">
          {shortcuts.map((shortcut, index) => (
            <div
              key={index}
              className="flex items-center justify-between p-3 bg-muted/50 rounded-lg"
            >
              <span className="text-sm">{shortcut.action}</span>
              <div className="flex items-center gap-1">
                {shortcut.keys.map((key, i) => (
                  <kbd
                    key={i}
                    className="px-2 py-1 bg-background border rounded text-xs font-mono"
                  >
                    {key}
                  </kbd>
                ))}
              </div>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  )
}

// ============================================================================
// MAIN PAGE
// ============================================================================
export default function InputPage() {
  return (
    <div className="space-y-8 relative">
      {/* Background Effects */}
      <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
        <div className="orb-cyan -top-40 -left-40 opacity-20" />
        <div className="orb-primary bottom-40 -right-40 opacity-20" />
      </div>

      <PageHeader
        title="Input Components"
        description="Advanced inputs with slash commands, mentions, voice, and AI features"
        icon={Keyboard}
        badge="Real Components"
      />

      <Tabs defaultValue="slash-commands" className="w-full">
        <TabsList className="mb-6 flex-wrap h-auto gap-2 p-1 glass-panel">
          <TabsTrigger value="slash-commands">Slash Commands</TabsTrigger>
          <TabsTrigger value="mentions">Mentions</TabsTrigger>
          <TabsTrigger value="advanced">Advanced Input</TabsTrigger>
          <TabsTrigger value="ai-textarea">AI Textarea</TabsTrigger>
          <TabsTrigger value="voice">Voice Input</TabsTrigger>
          <TabsTrigger value="shortcuts">Shortcuts</TabsTrigger>
        </TabsList>

        <TabsContent value="slash-commands">
          <ComponentSection
            title="Slash Commands"
            description="Functional slash command menu with keyboard navigation"
          >
            <SlashCommandsDemo />
          </ComponentSection>
        </TabsContent>

        <TabsContent value="mentions">
          <ComponentSection
            title="Mention System"
            description="Working @mention autocomplete with fuzzy search"
          >
            <MentionsComponentDemo />
          </ComponentSection>
        </TabsContent>

        <TabsContent value="advanced">
          <ComponentSection
            title="Advanced Chat Input"
            description="Combined input with all features integrated"
          >
            <AdvancedInputDemo />
          </ComponentSection>
        </TabsContent>

        <TabsContent value="ai-textarea">
          <ComponentSection
            title="AI Textarea"
            description="Smart autocomplete powered by AI"
          >
            <AITextareaDemo />
          </ComponentSection>
        </TabsContent>

        <TabsContent value="voice">
          <ComponentSection
            title="Voice Input"
            description="Speech-to-text capabilities"
          >
            <VoiceInputDemo />
          </ComponentSection>
        </TabsContent>

        <TabsContent value="shortcuts">
          <ComponentSection
            title="Keyboard Shortcuts"
            description="Quick actions reference"
          >
            <KeyboardShortcutsDemo />
          </ComponentSection>
        </TabsContent>
      </Tabs>
    </div>
  )
}
