import type { KeyboardShortcutConfig } from './types'

/**
 * Default Keyboard Shortcuts for Chat Applications
 */

export const defaultChatShortcuts: KeyboardShortcutConfig[] = [
  {
    id: 'show-shortcuts',
    keys: ['?', 'shift+/'],
    description: 'Show keyboard shortcuts',
    category: 'Help',
    handler: () => {},
    priority: 100,
  },
  {
    id: 'command-palette',
    keys: 'mod+k',
    description: 'Open command palette',
    category: 'Navigation',
    handler: () => {},
    priority: 100,
  },
  {
    id: 'search',
    keys: ['/', 'mod+f'],
    description: 'Focus search',
    category: 'Navigation',
    handler: () => {},
    priority: 90,
  },
  {
    id: 'new-chat',
    keys: 'mod+n',
    description: 'Start new chat',
    category: 'Chat',
    handler: () => {},
    priority: 80,
  },
  {
    id: 'send-message',
    keys: 'mod+enter',
    description: 'Send message',
    category: 'Chat',
    handler: () => {},
    enableInInput: true,
    priority: 100,
  },
  {
    id: 'focus-input',
    keys: ['i', 'mod+i'],
    description: 'Focus message input',
    category: 'Chat',
    handler: () => {},
    priority: 70,
  },
  {
    id: 'escape',
    keys: 'escape',
    description: 'Close modal/Cancel action',
    category: 'General',
    handler: () => {},
    enableInInput: true,
    priority: 100,
  },
  {
    id: 'toggle-sidebar',
    keys: 'mod+b',
    description: 'Toggle sidebar',
    category: 'Navigation',
    handler: () => {},
    priority: 60,
  },
  {
    id: 'scroll-to-bottom',
    keys: ['end', 'mod+down'],
    description: 'Scroll to bottom',
    category: 'Navigation',
    handler: () => {},
    priority: 50,
  },
  {
    id: 'scroll-to-top',
    keys: ['home', 'mod+up'],
    description: 'Scroll to top',
    category: 'Navigation',
    handler: () => {},
    priority: 50,
  },
  {
    id: 'copy-last-message',
    keys: 'mod+shift+c',
    description: 'Copy last assistant message',
    category: 'Chat',
    handler: () => {},
    priority: 70,
  },
  {
    id: 'regenerate',
    keys: 'mod+shift+r',
    description: 'Regenerate last response',
    category: 'Chat',
    handler: () => {},
    priority: 70,
  },
  // Vim-style navigation sequences
  {
    id: 'go-to-settings',
    keys: 'g s',
    description: 'Go to settings',
    category: 'Navigation',
    handler: () => {},
    priority: 40,
  },
  {
    id: 'go-to-home',
    keys: 'g h',
    description: 'Go to home',
    category: 'Navigation',
    handler: () => {},
    priority: 40,
  },
  {
    id: 'go-to-chats',
    keys: 'g c',
    description: 'Go to chat list',
    category: 'Navigation',
    handler: () => {},
    priority: 40,
  },
]
