/**
 * Type declarations to fix lucide-react compatibility with TypeScript 5.x + React 18
 * 
 * This file resolves TS2786 errors when using lucide-react icons as JSX components.
 */

declare module 'lucide-react' {
  import type { SVGProps, FC } from 'react'

  export interface LucideProps extends Partial<Omit<SVGProps<SVGSVGElement>, 'ref'>> {
    size?: string | number
    absoluteStrokeWidth?: boolean
  }

  export type LucideIcon = FC<LucideProps>

  // Export all icons as proper React components
  export const ArrowLeft: LucideIcon
  export const ArrowRight: LucideIcon  
  export const ShoppingCart: LucideIcon
  export const Code: LucideIcon
  export const Code2: LucideIcon
  export const Users: LucideIcon
  export const FileText: LucideIcon
  export const Mail: LucideIcon
  export const Heart: LucideIcon
  export const DollarSign: LucideIcon
  export const GraduationCap: LucideIcon
  export const BarChart3: LucideIcon
  export const Microscope: LucideIcon
  export const MessageSquare: LucideIcon
  export const Bug: LucideIcon
  export const Terminal: LucideIcon
  export const GitBranch: LucideIcon
  export const BookOpen: LucideIcon
  export const CheckCircle: LucideIcon
  export const Award: LucideIcon
  export const Star: LucideIcon
  export const Cpu: LucideIcon
  export const HeartPulse: LucideIcon
  export const Stethoscope: LucideIcon
  export const PlusCircle: LucideIcon
  export const Sparkles: LucideIcon
  export const TrendingUp: LucideIcon
  export const Bot: LucideIcon
  export const Send: LucideIcon
  export const Copy: LucideIcon
  export const Check: LucideIcon
  export const ThumbsUp: LucideIcon
  export const ThumbsDown: LucideIcon
  export const MoreHorizontal: LucideIcon
  export const X: LucideIcon
  export const Upload: LucideIcon
  export const Download: LucideIcon
  export const Settings: LucideIcon
  export const Search: LucideIcon
  export const Filter: LucideIcon
  export const SortAsc: LucideIcon
  export const SortDesc: LucideIcon
  export const Calendar: LucideIcon
  export const Clock: LucideIcon
  export const AlertTriangle: LucideIcon
  export const AlertCircle: LucideIcon
  export const Info: LucideIcon
  export const HelpCircle: LucideIcon
  export const ExternalLink: LucideIcon
  export const Link: LucideIcon
  export const Unlink: LucideIcon
  export const Eye: LucideIcon
  export const EyeOff: LucideIcon
  export const Lock: LucideIcon
  export const Unlock: LucideIcon
  export const Key: LucideIcon
  export const Shield: LucideIcon
  export const Database: LucideIcon
  export const Server: LucideIcon
  export const Cloud: LucideIcon
  export const Globe: LucideIcon
  export const Wifi: LucideIcon
  export const WifiOff: LucideIcon
  export const Zap: LucideIcon
  export const Activity: LucideIcon
  export const Loader2: LucideIcon
  export const RefreshCw: LucideIcon
  export const RotateCw: LucideIcon
  export const Trash: LucideIcon
  export const Trash2: LucideIcon
  export const Edit: LucideIcon
  export const Edit2: LucideIcon
  export const Edit3: LucideIcon
  export const Save: LucideIcon
  export const Plus: LucideIcon
  export const Minus: LucideIcon
  export const ChevronLeft: LucideIcon
  export const ChevronRight: LucideIcon
  export const ChevronUp: LucideIcon
  export const ChevronDown: LucideIcon
  export const ChevronsLeft: LucideIcon
  export const ChevronsRight: LucideIcon
  export const ChevronsUp: LucideIcon
  export const ChevronsDown: LucideIcon
  export const Menu: LucideIcon
  export const MoreVertical: LucideIcon
  export const Circle: LucideIcon
  export const CheckCircle2: LucideIcon
  export const XCircle: LucideIcon
  export const AlertOctagon: LucideIcon
  export const Inbox: LucideIcon
  export const MailOpen: LucideIcon
  export const MessageCircle: LucideIcon
  export const Bell: LucideIcon
  export const BellOff: LucideIcon
  export const Bookmark: LucideIcon
  export const Flag: LucideIcon
  export const Tag: LucideIcon
  export const Image: LucideIcon
  export const File: LucideIcon
  export const FileCode: LucideIcon
  export const Folder: LucideIcon
  export const FolderOpen: LucideIcon
  export const Package: LucideIcon
  export const Archive: LucideIcon
  export const Layers: LucideIcon
  export const Layout: LucideIcon
  export const Grid: LucideIcon
  export const List: LucideIcon
  export const Columns: LucideIcon
  export const Rows: LucideIcon
  export const PanelLeft: LucideIcon
  export const PanelRight: LucideIcon
  export const SidebarOpen: LucideIcon
  export const SidebarClose: LucideIcon
  export const Maximize: LucideIcon
  export const Minimize: LucideIcon
  export const Maximize2: LucideIcon
  export const Minimize2: LucideIcon
  export const ZoomIn: LucideIcon
  export const ZoomOut: LucideIcon
  export const User: LucideIcon
  export const UserPlus: LucideIcon
  export const UserMinus: LucideIcon
  export const UserCheck: LucideIcon
  export const UserX: LucideIcon
  export const LogIn: LucideIcon
  export const LogOut: LucideIcon
  export const Home: LucideIcon
  export const Building: LucideIcon
  export const Briefcase: LucideIcon
  export const Palette: LucideIcon
  export const Paintbrush: LucideIcon
  export const Droplet: LucideIcon
  export const Sun: LucideIcon
  export const Moon: LucideIcon
  export const Monitor: LucideIcon
  export const Smartphone: LucideIcon
  export const Tablet: LucideIcon
  export const Laptop: LucideIcon
  export const Watch: LucideIcon
  export const Bluetooth: LucideIcon
  export const Cast: LucideIcon
  export const Printer: LucideIcon
  export const Camera: LucideIcon
  export const Video: LucideIcon
  export const VideoOff: LucideIcon
  export const Mic: LucideIcon
  export const MicOff: LucideIcon
  export const Volume: LucideIcon
  export const Volume1: LucideIcon
  export const Volume2: LucideIcon
  export const VolumeX: LucideIcon
  export const Play: LucideIcon
  export const Pause: LucideIcon
  export const StopCircle: LucideIcon
  export const SkipBack: LucideIcon
  export const SkipForward: LucideIcon
  export const Repeat: LucideIcon
  export const Repeat1: LucideIcon
  export const Shuffle: LucideIcon
  export const Music: LucideIcon
  export const Radio: LucideIcon
  export const Disc: LucideIcon
  export const Film: LucideIcon
  export const Tv: LucideIcon
  export const Gamepad2: LucideIcon
  export const Headphones: LucideIcon
  export const Hash: LucideIcon
  export const AtSign: LucideIcon
  export const Percent: LucideIcon
  export const Ampersand: LucideIcon
  export const DollarCircle: LucideIcon
  export const Euro: LucideIcon
  export const Pound: LucideIcon
  export const Yen: LucideIcon
  export const Bitcoin: LucideIcon
  export const CreditCard: LucideIcon
  export const Wallet: LucideIcon
  export const Receipt: LucideIcon
  export const Gift: LucideIcon
  export const ShoppingBag: LucideIcon
  export const Package2: LucideIcon
  export const Truck: LucideIcon
  export const Plane: LucideIcon
  export const Ship: LucideIcon
  export const Car: LucideIcon
  export const Bike: LucideIcon
  export const Bus: LucideIcon
  export const Train: LucideIcon
  export const Tram: LucideIcon
  export const Map: LucideIcon
  export const MapPin: LucideIcon
  export const Navigation: LucideIcon
  export const Compass: LucideIcon
  export const Target: LucideIcon
  export const Crosshair: LucideIcon
  export const Anchor: LucideIcon
  export const Rocket: LucideIcon
  export const Satellite: LucideIcon
  export const Network: LucideIcon
  export const Workflow: LucideIcon
  export const PieChart: LucideIcon
  export const Command: LucideIcon
  export const Lightbulb: LucideIcon
  export const Accessibility: LucideIcon
  export const BarChart: LucideIcon
  export const BarChart2: LucideIcon
  export const BarChart4: LucideIcon
  export const LineChart: LucideIcon
  export const AreaChart: LucideIcon
  export const Timer: LucideIcon
  export const Hourglass: LucideIcon
  export const Gauge: LucideIcon
  export const PhoneCall: LucideIcon
  export const Phone: LucideIcon
  export const PhoneOff: LucideIcon
  export const PhoneIncoming: LucideIcon
  export const PhoneOutgoing: LucideIcon
  export const Voicemail: LucideIcon
  export const MessageSquareText: LucideIcon
  export const MessageSquareDashed: LucideIcon
  export const MessageSquarePlus: LucideIcon
  export const MessagesSquare: LucideIcon
  export const MailCheck: LucideIcon
  export const MailPlus: LucideIcon
  export const MailMinus: LucideIcon
  export const MailX: LucideIcon
  export const Inbox: LucideIcon
  export const Send: LucideIcon
  export const SendHorizontal: LucideIcon
  export const Reply: LucideIcon
  export const ReplyAll: LucideIcon
  export const Forward: LucideIcon
  export const Paperclip: LucideIcon
  export const Link2: LucideIcon
  export const Link2Off: LucideIcon
  export const Box: LucideIcon
  export const Wrench: LucideIcon
  export const TestTube: LucideIcon
  export const Share2: LucideIcon
}
