/**
 * Search Index
 *
 * Auto-generated search data for the documentation site.
 * Generated on: 2026-01-11T05:25:02.899Z
 * Total items: 384
 *
 * DO NOT EDIT MANUALLY - Run 'npm run generate-search-index' to regenerate
 */

export interface SearchItem {
  title: string
  type:
    | 'component'
    | 'hook'
    | 'guide'
    | 'example'
    | 'cookbook'
    | 'concept'
    | 'deployment'
    | 'integration'
  href: string
  description: string
  category?: string
}

export const searchData: SearchItem[] = [
  {
    title: '@clarity-chat/codemods',
    type: 'guide',
    href: '/tools/codemods',
    description: '',
    category: 'tools',
  },
  {
    title: '@clarity-chat/dev-tools',
    type: 'guide',
    href: '/tools/dev-tools',
    description: '',
    category: 'tools',
  },
  {
    title: 'About Clarity Chat',
    type: 'guide',
    href: '/about',
    description: '',
    category: 'about',
  },
  {
    title: 'Accessibility',
    type: 'guide',
    href: '/learn/guides/accessibility',
    description: '',
    category: 'learn',
  },
  {
    title: 'Accessibility Basics',
    type: 'guide',
    href: '/guides/accessibility-basics',
    description: '',
    category: 'guides',
  },
  {
    title: 'Adding RAG to Your Chatbot',
    type: 'guide',
    href: '/learn/tutorials/adding-rag',
    description: '',
    category: 'learn',
  },
  {
    title: 'Agent System Guide',
    type: 'guide',
    href: '/guides/agents',
    description: '',
    category: 'guides',
  },
  {
    title: 'AI Assistant Template',
    type: 'guide',
    href: '/reference/templates/ai-assistant',
    description: '',
    category: 'reference',
  },
  {
    title: 'API Cheat Sheet',
    type: 'guide',
    href: '/reference/cheat-sheet',
    description: '',
    category: 'reference',
  },
  {
    title: 'API Quick Reference',
    type: 'guide',
    href: '/reference/quick-reference',
    description: '',
    category: 'reference',
  },
  {
    title: 'API Reference',
    type: 'guide',
    href: '/reference',
    description: '',
    category: 'reference',
  },
  {
    title: 'API Reference',
    type: 'guide',
    href: '/reference/api',
    description: '',
    category: 'reference',
  },
  {
    title: 'Architecture & Design Patterns',
    type: 'guide',
    href: '/learn/architecture',
    description: '',
    category: 'learn',
  },
  {
    title: 'Beautiful CLI',
    type: 'guide',
    href: '/tools/cli',
    description: '',
    category: 'tools',
  },
  {
    title: 'Best Practices Guide',
    type: 'guide',
    href: '/guides/best-practices',
    description: '',
    category: 'guides',
  },
  {
    title: 'Building Your First Chatbot',
    type: 'guide',
    href: '/learn/tutorials/building-first-chatbot',
    description: '',
    category: 'learn',
  },
  {
    title: 'Bundle &amp; Performance Analysis',
    type: 'guide',
    href: '/tools/analysis',
    description: '',
    category: 'tools',
  },
  {
    title: 'Bundle Size Optimization',
    type: 'guide',
    href: '/learn/guides/bundle-size',
    description: '',
    category: 'learn',
  },
  {
    title: 'CI/CD Reference Pipeline',
    type: 'guide',
    href: '/tools/cicd',
    description: '',
    category: 'tools',
  },
  {
    title: 'Clarity Chat – VS Code Extension',
    type: 'guide',
    href: '/tools/vscode',
    description: '',
    category: 'tools',
  },
  {
    title: 'Clarity Chat Case Studies',
    type: 'guide',
    href: '/enterprise/case-studies',
    description: '',
    category: 'enterprise',
  },
  {
    title: 'Clarity Chat Pricing Guide',
    type: 'guide',
    href: '/enterprise/pricing',
    description: '',
    category: 'enterprise',
  },
  {
    title: 'Code Assistant Template',
    type: 'guide',
    href: '/reference/templates/code-assistant',
    description: '',
    category: 'reference',
  },
  {
    title: 'Code-helper Template',
    type: 'guide',
    href: '/reference/templates/code-helper',
    description: '',
    category: 'reference',
  },
  {
    title: 'Commercial Documentation',
    type: 'guide',
    href: '/commercial',
    description: '',
    category: 'commercial',
  },
  {
    title: 'Common Patterns',
    type: 'guide',
    href: '/learn/guides/common-patterns',
    description: '',
    category: 'learn',
  },
  {
    title: 'Component Hierarchy',
    type: 'guide',
    href: '/guides/component-hierarchy',
    description: '',
    category: 'guides',
  },
  {
    title: 'Component Optimization',
    type: 'guide',
    href: '/guides/component-optimization',
    description: '',
    category: 'guides',
  },
  {
    title: 'Components API',
    type: 'guide',
    href: '/reference/api/components',
    description: '',
    category: 'reference',
  },
  {
    title: 'Composition Patterns',
    type: 'guide',
    href: '/guides/composition-patterns',
    description: '',
    category: 'guides',
  },
  {
    title: 'Configuration',
    type: 'guide',
    href: '/reference/api/configuration',
    description: '',
    category: 'reference',
  },
  {
    title: 'Contributing to Clarity Chat',
    type: 'guide',
    href: '/contributing',
    description: '',
    category: 'contributing',
  },
  {
    title: 'createMemoryStore',
    type: 'guide',
    href: '/reference/utilities/create-memory-store',
    description: '',
    category: 'reference',
  },
  {
    title: 'Creative-writing Template',
    type: 'guide',
    href: '/reference/templates/creative-writing',
    description: '',
    category: 'reference',
  },
  {
    title: 'Customer Support Template',
    type: 'guide',
    href: '/reference/templates/customer-support',
    description: '',
    category: 'reference',
  },
  {
    title: 'Customization',
    type: 'guide',
    href: '/guides/customization',
    description: '',
    category: 'guides',
  },
  {
    title: 'Customization Strategies',
    type: 'guide',
    href: '/guides/customization-strategies',
    description: '',
    category: 'guides',
  },
  {
    title: 'Data Flow',
    type: 'guide',
    href: '/guides/data-flow',
    description: '',
    category: 'guides',
  },
  {
    title: 'Data-analyst Template',
    type: 'guide',
    href: '/reference/templates/data-analyst',
    description: '',
    category: 'reference',
  },
  {
    title: 'Developer Tools',
    type: 'guide',
    href: '/tools',
    description: '',
    category: 'tools',
  },
  {
    title: 'Documentation Bot Template',
    type: 'guide',
    href: '/reference/templates/documentation-bot',
    description: '',
    category: 'reference',
  },
  {
    title: 'Education-tutor Template',
    type: 'guide',
    href: '/reference/templates/education-tutor',
    description: '',
    category: 'reference',
  },
  {
    title: 'Enterprise Accessibility',
    type: 'guide',
    href: '/guides/accessibility',
    description: '',
    category: 'guides',
  },
  {
    title: 'Enterprise Deployment',
    type: 'guide',
    href: '/guides/enterprise-deployment',
    description: '',
    category: 'guides',
  },
  {
    title: 'Enterprise Features',
    type: 'guide',
    href: '/enterprise-standalone',
    description: '',
    category: 'enterprise-standalone',
  },
  {
    title: 'Enterprise Features',
    type: 'guide',
    href: '/enterprise',
    description: '',
    category: 'enterprise',
  },
  {
    title: 'Error Reporter',
    type: 'guide',
    href: '/reference/utilities/error-reporter',
    description: '',
    category: 'reference',
  },
  {
    title: 'Evaluation Workflow',
    type: 'guide',
    href: '/guides/evaluation-workflow',
    description: '',
    category: 'guides',
  },
  {
    title: 'Examples Catalog',
    type: 'guide',
    href: '/examples-catalog',
    description: '',
    category: 'examples-catalog',
  },
  {
    title: 'export-utils',
    type: 'guide',
    href: '/reference/utilities/export-utils',
    description: '',
    category: 'reference',
  },
  {
    title: 'Frequently Asked Questions',
    type: 'guide',
    href: '/learn/faq',
    description: '',
    category: 'learn',
  },
  {
    title: 'Guides',
    type: 'guide',
    href: '/guides',
    description: '',
    category: 'guides',
  },
  {
    title: 'Guides',
    type: 'guide',
    href: '/learn/guides',
    description: '',
    category: 'learn',
  },
  {
    title: 'Hook Dependencies',
    type: 'guide',
    href: '/guides/hook-dependencies',
    description: '',
    category: 'guides',
  },
  {
    title: 'Hook Performance',
    type: 'guide',
    href: '/guides/hook-performance',
    description: '',
    category: 'guides',
  },
  {
    title: 'Hooks API',
    type: 'guide',
    href: '/reference/api/hooks',
    description: '',
    category: 'reference',
  },
  {
    title: 'Installation',
    type: 'guide',
    href: '/learn/installation',
    description: '',
    category: 'learn',
  },
  {
    title: 'Integration Guide',
    type: 'guide',
    href: '/guides/integration',
    description: '',
    category: 'guides',
  },
  {
    title: 'Interactive Examples',
    type: 'guide',
    href: '/guides/interactive',
    description: '',
    category: 'guides',
  },
  {
    title: 'Interactive Playground',
    type: 'guide',
    href: '/playground',
    description: '',
    category: 'playground',
  },
  {
    title: 'Interactive Playground',
    type: 'guide',
    href: '/tools/playground',
    description: '',
    category: 'tools',
  },
  {
    title: 'Learn Clarity Chat',
    type: 'guide',
    href: '/learn',
    description: '',
    category: 'learn',
  },
  {
    title: 'Live Playground',
    type: 'guide',
    href: '/playground-demo',
    description: '',
    category: 'playground-demo',
  },
  {
    title: 'Memory System Deep Dive',
    type: 'guide',
    href: '/guides/memory',
    description: '',
    category: 'guides',
  },
  {
    title: 'MemoryService (`@clarity-chat/memory`)',
    type: 'guide',
    href: '/reference/services/memory-service',
    description: '',
    category: 'reference',
  },
  {
    title: 'Migrate from Vercel AI SDK',
    type: 'guide',
    href: '/learn/migration/from-vercel-ai-sdk',
    description: '',
    category: 'learn',
  },
  {
    title: 'MIT License',
    type: 'guide',
    href: '/license',
    description: '',
    category: 'license',
  },
  {
    title: 'Mobile Experience',
    type: 'guide',
    href: '/guides/mobile',
    description: '',
    category: 'guides',
  },
  {
    title: 'Mobile Optimization Guide',
    type: 'guide',
    href: '/guides/mobile-optimization',
    description: '',
    category: 'guides',
  },
  {
    title: 'Model Adapters API',
    type: 'guide',
    href: '/reference/api/model-adapters',
    description: '',
    category: 'reference',
  },
  {
    title: 'Multi-Tenancy Setup',
    type: 'guide',
    href: '/guides/multi-tenancy-setup',
    description: '',
    category: 'guides',
  },
  {
    title: 'Performance',
    type: 'guide',
    href: '/learn/guides/performance',
    description: '',
    category: 'learn',
  },
  {
    title: 'Performance Optimization',
    type: 'guide',
    href: '/guides/performance',
    description: '',
    category: 'guides',
  },
  {
    title: 'Performance Optimization Patterns',
    type: 'guide',
    href: '/guides/performance-optimization-patterns',
    description: '',
    category: 'guides',
  },
  {
    title: 'Playground Guide',
    type: 'guide',
    href: '/playground/guide',
    description: '',
    category: 'playground',
  },
  {
    title: 'Primitives API Documentation',
    type: 'guide',
    href: '/reference/api/primitives',
    description: '',
    category: 'reference',
  },
  {
    title: 'Production Deployment',
    type: 'guide',
    href: '/guides/production-deployment',
    description: '',
    category: 'guides',
  },
  {
    title: 'Prompt Caching Guide',
    type: 'guide',
    href: '/guides/prompt-caching',
    description: '',
    category: 'guides',
  },
  {
    title: 'Prompt Testing',
    type: 'guide',
    href: '/guides/prompt-testing',
    description: '',
    category: 'guides',
  },
  {
    title: 'Provider Pattern',
    type: 'guide',
    href: '/guides/provider-pattern',
    description: '',
    category: 'guides',
  },
  {
    title: 'Quick Start',
    type: 'guide',
    href: '/learn/quick-start',
    description: '',
    category: 'learn',
  },
  {
    title: 'RAG Pipeline Guide',
    type: 'guide',
    href: '/guides/rag',
    description: '',
    category: 'guides',
  },
  {
    title: 'React Components API Documentation',
    type: 'guide',
    href: '/reference/api/react-components',
    description: '',
    category: 'reference',
  },
  {
    title: 'Research',
    type: 'guide',
    href: '/research',
    description: '',
    category: 'research',
  },
  {
    title: 'ROI Calculator',
    type: 'guide',
    href: '/tools/roi-calculator',
    description: '',
    category: 'tools',
  },
  {
    title: 'Safety Review',
    type: 'guide',
    href: '/guides/safety-review',
    description: '',
    category: 'guides',
  },
  {
    title: 'Sales-assistant Template',
    type: 'guide',
    href: '/reference/templates/sales-assistant',
    description: '',
    category: 'reference',
  },
  {
    title: 'Seat Management',
    type: 'guide',
    href: '/guides/seat-management',
    description: '',
    category: 'guides',
  },
  {
    title: 'Security &amp; Compliance',
    type: 'guide',
    href: '/guides/security',
    description: '',
    category: 'guides',
  },
  {
    title: 'Security Playground',
    type: 'guide',
    href: '/playground/security',
    description: '',
    category: 'playground',
  },
  {
    title: 'See Clarity Chat in Action',
    type: 'guide',
    href: '/demos',
    description: '',
    category: 'demos',
  },
  {
    title: 'Services',
    type: 'guide',
    href: '/reference/services',
    description: '',
    category: 'reference',
  },
  {
    title: 'SSO Configuration',
    type: 'guide',
    href: '/guides/sso-configuration',
    description: '',
    category: 'guides',
  },
  {
    title: 'Standalone API Documentation',
    type: 'guide',
    href: '/reference/api-standalone',
    description: '',
    category: 'reference',
  },
  {
    title: 'State Management',
    type: 'guide',
    href: '/guides/state-management',
    description: '',
    category: 'guides',
  },
  {
    title: 'State Management Patterns',
    type: 'guide',
    href: '/guides/state-management-patterns',
    description: '',
    category: 'guides',
  },
  {
    title: 'Streaming & Transport Guide',
    type: 'guide',
    href: '/guides/streaming',
    description: '',
    category: 'guides',
  },
  {
    title: 'Streaming Components API',
    type: 'guide',
    href: '/reference/api/streaming-components',
    description: '',
    category: 'reference',
  },
  {
    title: 'Styling Clarity Chat',
    type: 'guide',
    href: '/learn/guides/styling',
    description: '',
    category: 'learn',
  },
  {
    title: 'Support Bot Template',
    type: 'guide',
    href: '/reference/templates/support-bot',
    description: '',
    category: 'reference',
  },
  {
    title: 'Templates',
    type: 'guide',
    href: '/reference/templates',
    description: '',
    category: 'reference',
  },
  {
    title: 'Testing Guide',
    type: 'guide',
    href: '/learn/guides/testing',
    description: '',
    category: 'learn',
  },
  {
    title: 'Testing Strategy',
    type: 'guide',
    href: '/guides/testing',
    description: '',
    category: 'guides',
  },
  {
    title: 'Testing Toolkit',
    type: 'guide',
    href: '/tools/testing',
    description: '',
    category: 'tools',
  },
  {
    title: 'Theme Builder',
    type: 'guide',
    href: '/reference/utilities/theme-builder',
    description: '',
    category: 'reference',
  },
  {
    title: 'Token Counter Utility',
    type: 'guide',
    href: '/reference/utilities/token-counter-util',
    description: '',
    category: 'reference',
  },
  {
    title: 'Token Optimization Guide',
    type: 'guide',
    href: '/guides/token-optimization',
    description: '',
    category: 'guides',
  },
  {
    title: 'Tool Integration Guide',
    type: 'guide',
    href: '/guides/tool-integration',
    description: '',
    category: 'guides',
  },
  {
    title: 'TOON Format Utilities',
    type: 'guide',
    href: '/reference/utilities/toon-format',
    description: '',
    category: 'reference',
  },
  {
    title: 'Troubleshooting',
    type: 'guide',
    href: '/learn/troubleshooting',
    description: '',
    category: 'learn',
  },
  {
    title: 'Tutorial: Build a Complete Chat App',
    type: 'guide',
    href: '/learn/tutorial',
    description: '',
    category: 'learn',
  },
  {
    title: 'Type Definitions',
    type: 'guide',
    href: '/reference/api/types',
    description: '',
    category: 'reference',
  },
  {
    title: 'TypeScript',
    type: 'guide',
    href: '/learn/guides/typescript',
    description: '',
    category: 'learn',
  },
  {
    title: 'Utilities',
    type: 'guide',
    href: '/reference/utilities',
    description: '',
    category: 'reference',
  },
  {
    title: 'Utilities',
    type: 'guide',
    href: '/reference/api/utilities',
    description: '',
    category: 'reference',
  },
  {
    title: 'What&apos;s New',
    type: 'guide',
    href: '/learn/whats-new',
    description: '',
    category: 'learn',
  },
  {
    title: 'Why Clarity Chat?',
    type: 'guide',
    href: '/why-clarity',
    description: '',
    category: 'why-clarity',
  },
  {
    title: 'Why Clarity Chat?',
    type: 'guide',
    href: '/learn/why-clarity',
    description: '',
    category: 'learn',
  },
  {
    title: 'ABTestingDashboard',
    type: 'component',
    href: '/reference/components/ab-testing-dashboard',
    description: '',
    category: 'reference',
  },
  {
    title: 'AdvancedChatInput',
    type: 'component',
    href: '/reference/components/advanced-chat-input',
    description: '',
    category: 'reference',
  },
  {
    title: 'AdvancedMessageSearch',
    type: 'component',
    href: '/reference/components/advanced-message-search',
    description: '',
    category: 'reference',
  },
  {
    title: 'AgentRunFeed',
    type: 'component',
    href: '/reference/components/agent-run-feed',
    description: '',
    category: 'reference',
  },
  {
    title: 'Animated List',
    type: 'component',
    href: '/reference/components/animated-list',
    description: '',
    category: 'reference',
  },
  {
    title: 'ApiTokenManager',
    type: 'component',
    href: '/reference/components/api-token-manager',
    description: '',
    category: 'reference',
  },
  {
    title: 'AuthTenantDashboard',
    type: 'component',
    href: '/reference/components/auth-tenant-dashboard',
    description: '',
    category: 'reference',
  },
  {
    title: 'Avatar',
    type: 'component',
    href: '/reference/components/avatar',
    description: '',
    category: 'reference',
  },
  {
    title: 'Badge',
    type: 'component',
    href: '/reference/components/badge',
    description: '',
    category: 'reference',
  },
  {
    title: 'BatteryIndicator',
    type: 'component',
    href: '/reference/components/battery-indicator',
    description: '',
    category: 'reference',
  },
  {
    title: 'Button',
    type: 'component',
    href: '/reference/components/button',
    description: '',
    category: 'reference',
  },
  {
    title: 'CalendarIntegration',
    type: 'component',
    href: '/reference/components/calendar-integration',
    description: '',
    category: 'reference',
  },
  {
    title: 'ChainOfThought',
    type: 'component',
    href: '/reference/components/chain-of-thought',
    description: '',
    category: 'reference',
  },
  {
    title: 'Chat Recipes',
    type: 'component',
    href: '/reference/components/chat-recipes',
    description: '',
    category: 'reference',
  },
  {
    title: 'ChatInput',
    type: 'component',
    href: '/reference/components/chat-input',
    description: '',
    category: 'reference',
  },
  {
    title: 'ChatLayout',
    type: 'component',
    href: '/reference/components/chat-layout',
    description: '',
    category: 'reference',
  },
  {
    title: 'ChatWindow',
    type: 'component',
    href: '/reference/components/chat-window',
    description: '',
    category: 'reference',
  },
  {
    title: 'Citation Card',
    type: 'component',
    href: '/reference/components/citation-card',
    description: '',
    category: 'reference',
  },
  {
    title: 'ClarityChat',
    type: 'component',
    href: '/reference/components/clarity-chat',
    description: '',
    category: 'reference',
  },
  {
    title: 'ClarityChatPresets',
    type: 'component',
    href: '/reference/components/clarity-chat-presets',
    description: '',
    category: 'reference',
  },
  {
    title: 'ClarityToolResult',
    type: 'component',
    href: '/reference/components/clarity-tool-result',
    description: '',
    category: 'reference',
  },
  {
    title: 'CodeBlock',
    type: 'component',
    href: '/reference/components/code-block',
    description: '',
    category: 'reference',
  },
  {
    title: 'CollaborativeEditor',
    type: 'component',
    href: '/reference/components/collaborative-editing',
    description: '',
    category: 'reference',
  },
  {
    title: 'Collapsible Section',
    type: 'component',
    href: '/reference/components/collapsible-section',
    description: '',
    category: 'reference',
  },
  {
    title: 'CommandPalette',
    type: 'component',
    href: '/reference/components/command-palette',
    description: '',
    category: 'reference',
  },
  {
    title: 'Component Library',
    type: 'component',
    href: '/reference/components',
    description: '',
    category: 'reference',
  },
  {
    title: 'Context Card',
    type: 'component',
    href: '/reference/components/context-card',
    description: '',
    category: 'reference',
  },
  {
    title: 'Context Manager',
    type: 'component',
    href: '/reference/components/context-manager',
    description: '',
    category: 'reference',
  },
  {
    title: 'Context Visualizer',
    type: 'component',
    href: '/reference/components/context-visualizer',
    description: '',
    category: 'reference',
  },
  {
    title: 'ContextMenu',
    type: 'component',
    href: '/reference/components/context-menu',
    description: '',
    category: 'reference',
  },
  {
    title: 'Conversation List - Clarity Chat',
    type: 'component',
    href: '/reference/components/conversation-list',
    description: '',
    category: 'reference',
  },
  {
    title: 'Conversation Timeline',
    type: 'component',
    href: '/reference/components/conversation-timeline',
    description: '',
    category: 'reference',
  },
  {
    title: 'ConversationAnalyticsDashboard',
    type: 'component',
    href: '/reference/components/conversation-analytics-dashboard',
    description: '',
    category: 'reference',
  },
  {
    title: 'ConversationBranchVisualizer',
    type: 'component',
    href: '/reference/components/conversation-branch-visualizer',
    description: '',
    category: 'reference',
  },
  {
    title: 'ConversationSummarizer',
    type: 'component',
    href: '/reference/components/conversation-summarizer',
    description: '',
    category: 'reference',
  },
  {
    title: 'Copy Button',
    type: 'component',
    href: '/reference/components/copy-button',
    description: '',
    category: 'reference',
  },
  {
    title: 'DocumentIntegration',
    type: 'component',
    href: '/reference/components/document-integration',
    description: '',
    category: 'reference',
  },
  {
    title: 'Draggable & DropZone',
    type: 'component',
    href: '/reference/components/draggable',
    description: '',
    category: 'reference',
  },
  {
    title: 'Drawer',
    type: 'component',
    href: '/reference/components/drawer',
    description: '',
    category: 'reference',
  },
  {
    title: 'EmailIntegration',
    type: 'component',
    href: '/reference/components/email-integration',
    description: '',
    category: 'reference',
  },
  {
    title: 'Empty State',
    type: 'component',
    href: '/reference/components/empty-state',
    description: '',
    category: 'reference',
  },
  {
    title: 'Error Boundary',
    type: 'component',
    href: '/reference/components/error-boundary',
    description: '',
    category: 'reference',
  },
  {
    title: 'Error Boundary Enhanced',
    type: 'component',
    href: '/reference/components/error-boundary-enhanced',
    description: '',
    category: 'reference',
  },
  {
    title: 'EvaluationDashboard',
    type: 'component',
    href: '/reference/components/evaluation-dashboard',
    description: '',
    category: 'reference',
  },
  {
    title: 'Export Dialog',
    type: 'component',
    href: '/reference/components/export-dialog',
    description: '',
    category: 'reference',
  },
  {
    title: 'Feedback Animation',
    type: 'component',
    href: '/reference/components/feedback-animation',
    description: '',
    category: 'reference',
  },
  {
    title: 'FileUpload',
    type: 'component',
    href: '/reference/components/file-upload',
    description: '',
    category: 'reference',
  },
  {
    title: 'Follow-Up Suggestions',
    type: 'component',
    href: '/reference/components/follow-up-suggestions',
    description: '',
    category: 'reference',
  },
  {
    title: 'HistoryManager',
    type: 'component',
    href: '/reference/components/history-manager',
    description: '',
    category: 'reference',
  },
  {
    title: 'Icons',
    type: 'component',
    href: '/reference/components/icons',
    description: '',
    category: 'reference',
  },
  {
    title: 'Input',
    type: 'component',
    href: '/reference/components/input',
    description: '',
    category: 'reference',
  },
  {
    title: 'Interactive Card',
    type: 'component',
    href: '/reference/components/interactive-card',
    description: '',
    category: 'reference',
  },
  {
    title: 'Keyboard Hint',
    type: 'component',
    href: '/reference/components/keyboard-hint',
    description: '',
    category: 'reference',
  },
  {
    title: 'Knowledge-base-viewer',
    type: 'component',
    href: '/reference/components/knowledge-base-viewer',
    description: '',
    category: 'reference',
  },
  {
    title: 'Link Preview',
    type: 'component',
    href: '/reference/components/link-preview',
    description: '',
    category: 'reference',
  },
  {
    title: 'MarkdownRendererEnhanced',
    type: 'component',
    href: '/reference/components/markdown-renderer-enhanced',
    description: '',
    category: 'reference',
  },
  {
    title: 'Memory Inspector',
    type: 'component',
    href: '/reference/components/memory-inspector',
    description: '',
    category: 'reference',
  },
  {
    title: 'MemoryProvider',
    type: 'component',
    href: '/reference/components/memory-provider',
    description: '',
    category: 'reference',
  },
  {
    title: 'MentionInput & MentionList',
    type: 'component',
    href: '/reference/components/mention-system',
    description: '',
    category: 'reference',
  },
  {
    title: 'Message',
    type: 'component',
    href: '/reference/components/message',
    description: '',
    category: 'reference',
  },
  {
    title: 'Message Search',
    type: 'component',
    href: '/reference/components/message-search',
    description: '',
    category: 'reference',
  },
  {
    title: 'Message-optimized',
    type: 'component',
    href: '/reference/components/message-optimized',
    description: '',
    category: 'reference',
  },
  {
    title: 'MessageActionsSecure',
    type: 'component',
    href: '/reference/components/message-actions-secure',
    description: '',
    category: 'reference',
  },
  {
    title: 'MessageList',
    type: 'component',
    href: '/reference/components/message-list',
    description: '',
    category: 'reference',
  },
  {
    title: 'MessageThreadView & ThreadList',
    type: 'component',
    href: '/reference/components/message-thread-view',
    description: '',
    category: 'reference',
  },
  {
    title: 'MobileOptimizedMessage & MobileChatWindow',
    type: 'component',
    href: '/reference/components/mobile-optimized-message',
    description: '',
    category: 'reference',
  },
  {
    title: 'ModelSelector',
    type: 'component',
    href: '/reference/components/model-selector',
    description: '',
    category: 'reference',
  },
  {
    title: 'Multi-Modal Preview',
    type: 'component',
    href: '/reference/components/multi-modal-preview',
    description: '',
    category: 'reference',
  },
  {
    title: 'NetworkStatus',
    type: 'component',
    href: '/reference/components/network-status',
    description: '',
    category: 'reference',
  },
  {
    title: 'OfflineChatSync',
    type: 'component',
    href: '/reference/components/offline-chat-sync',
    description: '',
    category: 'reference',
  },
  {
    title: 'OutputPreferenceSelector',
    type: 'component',
    href: '/reference/components/output-preference-selector',
    description: '',
    category: 'reference',
  },
  {
    title: 'PerformanceAnalyticsDashboard',
    type: 'component',
    href: '/reference/components/performance-analytics-dashboard',
    description: '',
    category: 'reference',
  },
  {
    title: 'PerformanceDashboard',
    type: 'component',
    href: '/reference/components/performance-dashboard',
    description: '',
    category: 'reference',
  },
  {
    title: 'Persona Panel',
    type: 'component',
    href: '/reference/components/persona-panel',
    description: '',
    category: 'reference',
  },
  {
    title: 'Popover',
    type: 'component',
    href: '/reference/components/popover',
    description: '',
    category: 'reference',
  },
  {
    title: 'Progress',
    type: 'component',
    href: '/reference/components/progress',
    description: '',
    category: 'reference',
  },
  {
    title: 'ProjectSidebar',
    type: 'component',
    href: '/reference/components/project-sidebar',
    description: '',
    category: 'reference',
  },
  {
    title: 'PromptContainer',
    type: 'component',
    href: '/reference/components/prompt-container',
    description: '',
    category: 'reference',
  },
  {
    title: 'PromptLibrary',
    type: 'component',
    href: '/reference/components/prompt-library',
    description: '',
    category: 'reference',
  },
  {
    title: 'PromptSuggestions',
    type: 'component',
    href: '/reference/components/prompt-suggestions',
    description: '',
    category: 'reference',
  },
  {
    title: 'PromptSuggestionsEnhanced',
    type: 'component',
    href: '/reference/components/prompt-suggestions-enhanced',
    description: '',
    category: 'reference',
  },
  {
    title: 'PromptTestHarness',
    type: 'component',
    href: '/reference/components/prompt-test-harness',
    description: '',
    category: 'reference',
  },
  {
    title: 'Response Quality Meter',
    type: 'component',
    href: '/reference/components/response-quality-meter',
    description: '',
    category: 'reference',
  },
  {
    title: 'RetryButton',
    type: 'component',
    href: '/reference/components/retry-button',
    description: '',
    category: 'reference',
  },
  {
    title: 'Ripple',
    type: 'component',
    href: '/reference/components/ripple',
    description: '',
    category: 'reference',
  },
  {
    title: 'Safety Status Card',
    type: 'component',
    href: '/reference/components/safety-status-card',
    description: '',
    category: 'reference',
  },
  {
    title: 'SafetyReviewConsole',
    type: 'component',
    href: '/reference/components/safety-review-console',
    description: '',
    category: 'reference',
  },
  {
    title: 'SeatInviteDialog',
    type: 'component',
    href: '/reference/components/seat-invite-dialog',
    description: '',
    category: 'reference',
  },
  {
    title: 'SemanticMessageSearch',
    type: 'component',
    href: '/reference/components/semantic-message-search',
    description: '',
    category: 'reference',
  },
  {
    title: 'Session Summary Card',
    type: 'component',
    href: '/reference/components/session-summary-card',
    description: '',
    category: 'reference',
  },
  {
    title: 'Settings Panel',
    type: 'component',
    href: '/reference/components/settings-panel',
    description: '',
    category: 'reference',
  },
  {
    title: 'Skeleton Loaders',
    type: 'component',
    href: '/reference/components/skeleton',
    description: '',
    category: 'reference',
  },
  {
    title: 'SourceCitation',
    type: 'component',
    href: '/reference/components/source-citation',
    description: '',
    category: 'reference',
  },
  {
    title: 'SSOConfigWizard',
    type: 'component',
    href: '/reference/components/sso-config-wizard',
    description: '',
    category: 'reference',
  },
  {
    title: 'StreamBlock',
    type: 'component',
    href: '/reference/components/stream-block',
    description: '',
    category: 'reference',
  },
  {
    title: 'StreamCancellation',
    type: 'component',
    href: '/reference/components/stream-cancellation',
    description: '',
    category: 'reference',
  },
  {
    title: 'StreamingMessage',
    type: 'component',
    href: '/reference/components/streaming-message',
    description: '',
    category: 'reference',
  },
  {
    title: 'StreamingProgress',
    type: 'component',
    href: '/reference/components/streaming-progress',
    description: '',
    category: 'reference',
  },
  {
    title: 'StreamingTextRenderer',
    type: 'component',
    href: '/reference/components/streaming-text-renderer',
    description: '',
    category: 'reference',
  },
  {
    title: 'SuggestionCards',
    type: 'component',
    href: '/reference/components/suggestion-cards',
    description: '',
    category: 'reference',
  },
  {
    title: 'Textarea',
    type: 'component',
    href: '/reference/components/textarea',
    description: '',
    category: 'reference',
  },
  {
    title: 'TextShimmer',
    type: 'component',
    href: '/reference/components/text-shimmer',
    description: '',
    category: 'reference',
  },
  {
    title: 'Theme Preview',
    type: 'component',
    href: '/reference/components/theme-preview',
    description: '',
    category: 'reference',
  },
  {
    title: 'Theme Selector',
    type: 'component',
    href: '/reference/components/theme-selector',
    description: '',
    category: 'reference',
  },
  {
    title: 'Theme Switcher',
    type: 'component',
    href: '/reference/components/theme-switcher',
    description: '',
    category: 'reference',
  },
  {
    title: 'Thinking Indicator',
    type: 'component',
    href: '/reference/components/thinking-indicator',
    description: '',
    category: 'reference',
  },
  {
    title: 'ThinkingBar',
    type: 'component',
    href: '/reference/components/thinking-bar',
    description: '',
    category: 'reference',
  },
  {
    title: 'Toast',
    type: 'component',
    href: '/reference/components/toast',
    description: '',
    category: 'reference',
  },
  {
    title: 'Token Counter',
    type: 'component',
    href: '/reference/components/token-counter',
    description: '',
    category: 'reference',
  },
  {
    title: 'TokenOptimizationBadge',
    type: 'component',
    href: '/reference/components/token-optimization-badge',
    description: '',
    category: 'reference',
  },
  {
    title: 'TokenOptimizationDashboard',
    type: 'component',
    href: '/reference/components/token-optimization-dashboard',
    description: '',
    category: 'reference',
  },
  {
    title: 'TokenOptimizationPanel',
    type: 'component',
    href: '/reference/components/token-optimization-panel',
    description: '',
    category: 'reference',
  },
  {
    title: 'ToolExecutionCard',
    type: 'component',
    href: '/reference/components/tool-execution-card',
    description: '',
    category: 'reference',
  },
  {
    title: 'ToolInvocationCard',
    type: 'component',
    href: '/reference/components/tool-invocation-card',
    description: '',
    category: 'reference',
  },
  {
    title: 'Tooltip',
    type: 'component',
    href: '/reference/components/tooltip',
    description: '',
    category: 'reference',
  },
  {
    title: 'TypingIndicator',
    type: 'component',
    href: '/reference/components/typing-indicator',
    description: '',
    category: 'reference',
  },
  {
    title: 'UsageDashboard',
    type: 'component',
    href: '/reference/components/usage-dashboard',
    description: '',
    category: 'reference',
  },
  {
    title: 'UserInteractionAnalytics',
    type: 'component',
    href: '/reference/components/user-interaction-analytics',
    description: '',
    category: 'reference',
  },
  {
    title: 'VirtualizedMessageList',
    type: 'component',
    href: '/reference/components/virtualized-message-list',
    description: '',
    category: 'reference',
  },
  {
    title: 'VoiceInput',
    type: 'component',
    href: '/reference/components/voice-input',
    description: '',
    category: 'reference',
  },
  {
    title: 'Workflow Suggestion List',
    type: 'component',
    href: '/reference/components/workflow-suggestion-list',
    description: '',
    category: 'reference',
  },
  {
    title: 'Compare Hooks',
    type: 'hook',
    href: '/reference/hooks/compare',
    description: '',
    category: 'reference',
  },
  {
    title: 'Hook Relationship Graph',
    type: 'hook',
    href: '/reference/hooks/graph',
    description: '',
    category: 'reference',
  },
  {
    title: 'Hooks API Reference',
    type: 'hook',
    href: '/reference/hooks',
    description: '',
    category: 'reference',
  },
  {
    title: 'use-deferred-search',
    type: 'hook',
    href: '/reference/hooks/use-deferred-search',
    description: '',
    category: 'reference',
  },
  {
    title: 'use-event-listener',
    type: 'hook',
    href: '/reference/hooks/use-event-listener',
    description: '',
    category: 'reference',
  },
  {
    title: 'use-haptic',
    type: 'hook',
    href: '/reference/hooks/use-haptic',
    description: '',
    category: 'reference',
  },
  {
    title: 'use-intersection-observer',
    type: 'hook',
    href: '/reference/hooks/use-intersection-observer',
    description: '',
    category: 'reference',
  },
  {
    title: 'use-mounted',
    type: 'hook',
    href: '/reference/hooks/use-mounted',
    description: '',
    category: 'reference',
  },
  {
    title: 'use-optimistic-message',
    type: 'hook',
    href: '/reference/hooks/use-optimistic-message',
    description: '',
    category: 'reference',
  },
  {
    title: 'use-performance',
    type: 'hook',
    href: '/reference/hooks/use-performance',
    description: '',
    category: 'reference',
  },
  {
    title: 'use-previous',
    type: 'hook',
    href: '/reference/hooks/use-previous',
    description: '',
    category: 'reference',
  },
  {
    title: 'use-realistic-typing',
    type: 'hook',
    href: '/reference/hooks/use-realistic-typing',
    description: '',
    category: 'reference',
  },
  {
    title: 'use-throttle',
    type: 'hook',
    href: '/reference/hooks/use-throttle',
    description: '',
    category: 'reference',
  },
  {
    title: 'use-toggle',
    type: 'hook',
    href: '/reference/hooks/use-toggle',
    description: '',
    category: 'reference',
  },
  {
    title: 'use-undo-redo',
    type: 'hook',
    href: '/reference/hooks/use-undo-redo',
    description: '',
    category: 'reference',
  },
  {
    title: 'use-window-size',
    type: 'hook',
    href: '/reference/hooks/use-window-size',
    description: '',
    category: 'reference',
  },
  {
    title: 'useABTesting',
    type: 'hook',
    href: '/reference/hooks/use-ab-testing',
    description: '',
    category: 'reference',
  },
  {
    title: 'useAgent',
    type: 'hook',
    href: '/reference/hooks/use-agent',
    description: '',
    category: 'reference',
  },
  {
    title: 'useAssistant',
    type: 'hook',
    href: '/reference/hooks/use-assistant',
    description: '',
    category: 'reference',
  },
  {
    title: 'useAutoScroll',
    type: 'hook',
    href: '/reference/hooks/use-auto-scroll',
    description: '',
    category: 'reference',
  },
  {
    title: 'useAvailabilityCheck',
    type: 'hook',
    href: '/reference/hooks/use-availability-check',
    description: '',
    category: 'reference',
  },
  {
    title: 'useBatteryAware',
    type: 'hook',
    href: '/reference/hooks/use-battery-aware',
    description: '',
    category: 'reference',
  },
  {
    title: 'useCalendarIntegration',
    type: 'hook',
    href: '/reference/hooks/use-calendar-integration',
    description: '',
    category: 'reference',
  },
  {
    title: 'useChat Hook',
    type: 'hook',
    href: '/reference/hooks/use-chat',
    description: '',
    category: 'reference',
  },
  {
    title: 'useChatEnhanced',
    type: 'hook',
    href: '/reference/hooks/use-chat-enhanced',
    description: '',
    category: 'reference',
  },
  {
    title: 'useChatHandlers',
    type: 'hook',
    href: '/reference/hooks/use-chat-handlers',
    description: '',
    category: 'reference',
  },
  {
    title: 'useChatOptimized',
    type: 'hook',
    href: '/reference/hooks/use-chat-optimized',
    description: '',
    category: 'reference',
  },
  {
    title: 'useCircuitBreaker',
    type: 'hook',
    href: '/reference/hooks/use-circuit-breaker',
    description: '',
    category: 'reference',
  },
  {
    title: 'useClarityChat',
    type: 'hook',
    href: '/reference/hooks/use-clarity-chat',
    description: '',
    category: 'reference',
  },
  {
    title: 'useClarityChatWithTools',
    type: 'hook',
    href: '/reference/hooks/use-clarity-chat-with-tools',
    description: '',
    category: 'reference',
  },
  {
    title: 'useClarityObject',
    type: 'hook',
    href: '/reference/hooks/use-clarity-object',
    description: '',
    category: 'reference',
  },
  {
    title: 'useClipboard Hook',
    type: 'hook',
    href: '/reference/hooks/use-clipboard',
    description: '',
    category: 'reference',
  },
  {
    title: 'useCollaborativeSession',
    type: 'hook',
    href: '/reference/hooks/use-collaborative-session',
    description: '',
    category: 'reference',
  },
  {
    title: 'useCommandPalette',
    type: 'hook',
    href: '/reference/hooks/use-command-palette',
    description: '',
    category: 'reference',
  },
  {
    title: 'useCompletion',
    type: 'hook',
    href: '/reference/hooks/use-completion',
    description: '',
    category: 'reference',
  },
  {
    title: 'useContextMonitor',
    type: 'hook',
    href: '/reference/hooks/use-context-monitor',
    description: '',
    category: 'reference',
  },
  {
    title: 'useConversationSharing',
    type: 'hook',
    href: '/reference/hooks/use-conversation-sharing',
    description: '',
    category: 'reference',
  },
  {
    title: 'useDashboardData',
    type: 'hook',
    href: '/reference/hooks/use-dashboard-data',
    description: '',
    category: 'reference',
  },
  {
    title: 'useDebounce',
    type: 'hook',
    href: '/reference/hooks/use-debounce',
    description: '',
    category: 'reference',
  },
  {
    title: 'useDesignTokens',
    type: 'hook',
    href: '/reference/hooks/use-design-tokens',
    description: '',
    category: 'reference',
  },
  {
    title: 'useDocumentIntegration',
    type: 'hook',
    href: '/reference/hooks/use-document-integration',
    description: '',
    category: 'reference',
  },
  {
    title: 'useEmailIntegration',
    type: 'hook',
    href: '/reference/hooks/use-email-integration',
    description: '',
    category: 'reference',
  },
  {
    title: 'useEmbeddings',
    type: 'hook',
    href: '/reference/hooks/use-embeddings',
    description: '',
    category: 'reference',
  },
  {
    title: 'useErrorRecovery',
    type: 'hook',
    href: '/reference/hooks/use-error-recovery',
    description: '',
    category: 'reference',
  },
  {
    title: 'useIndexedDB',
    type: 'hook',
    href: '/reference/hooks/use-indexed-db',
    description: '',
    category: 'reference',
  },
  {
    title: 'useInteractionTracking',
    type: 'hook',
    href: '/reference/hooks/use-interaction-tracking',
    description: '',
    category: 'reference',
  },
  {
    title: 'useKeyboardShortcuts',
    type: 'hook',
    href: '/reference/hooks/use-keyboard-shortcuts',
    description: '',
    category: 'reference',
  },
  {
    title: 'useLocalStorage',
    type: 'hook',
    href: '/reference/hooks/use-local-storage',
    description: '',
    category: 'reference',
  },
  {
    title: 'useMediaQuery',
    type: 'hook',
    href: '/reference/hooks/use-media-query',
    description: '',
    category: 'reference',
  },
  {
    title: 'useMemoryContext',
    type: 'hook',
    href: '/reference/hooks/use-memory-context',
    description: '',
    category: 'reference',
  },
  {
    title: 'useMentions',
    type: 'hook',
    href: '/reference/hooks/use-mentions',
    description: '',
    category: 'reference',
  },
  {
    title: 'useMessageOperations',
    type: 'hook',
    href: '/reference/hooks/use-message-operations',
    description: '',
    category: 'reference',
  },
  {
    title: 'useMobileKeyboard',
    type: 'hook',
    href: '/reference/hooks/use-mobile-keyboard',
    description: '',
    category: 'reference',
  },
  {
    title: 'useMobileOptimization',
    type: 'hook',
    href: '/reference/hooks/use-mobile-optimization',
    description: '',
    category: 'reference',
  },
  {
    title: 'useModelRouter',
    type: 'hook',
    href: '/reference/hooks/use-model-router',
    description: '',
    category: 'reference',
  },
  {
    title: 'useOfflineChat',
    type: 'hook',
    href: '/reference/hooks/use-offline-chat',
    description: '',
    category: 'reference',
  },
  {
    title: 'useOutputPreference',
    type: 'hook',
    href: '/reference/hooks/use-output-preference',
    description: '',
    category: 'reference',
  },
  {
    title: 'useRAGPipeline',
    type: 'hook',
    href: '/reference/hooks/use-rag-pipeline',
    description: '',
    category: 'reference',
  },
  {
    title: 'useRequestDeduplication',
    type: 'hook',
    href: '/reference/hooks/use-request-deduplication',
    description: '',
    category: 'reference',
  },
  {
    title: 'useRetryWithBackoff',
    type: 'hook',
    href: '/reference/hooks/use-retry-with-backoff',
    description: '',
    category: 'reference',
  },
  {
    title: 'useSmartCache',
    type: 'hook',
    href: '/reference/hooks/use-smart-cache',
    description: '',
    category: 'reference',
  },
  {
    title: 'useStreamableUI',
    type: 'hook',
    href: '/reference/hooks/use-streamable-ui',
    description: '',
    category: 'reference',
  },
  {
    title: 'useStreaming Hook',
    type: 'hook',
    href: '/reference/hooks/use-streaming',
    description: '',
    category: 'reference',
  },
  {
    title: 'useStreamingSSE',
    type: 'hook',
    href: '/reference/hooks/use-streaming-sse',
    description: '',
    category: 'reference',
  },
  {
    title: 'useStreamingWebSocket',
    type: 'hook',
    href: '/reference/hooks/use-streaming-websocket',
    description: '',
    category: 'reference',
  },
  {
    title: 'useStructuredInput',
    type: 'hook',
    href: '/reference/hooks/use-structured-input',
    description: '',
    category: 'reference',
  },
  {
    title: 'useTokenOptimization',
    type: 'hook',
    href: '/reference/hooks/use-token-optimization',
    description: '',
    category: 'reference',
  },
  {
    title: 'useTokenOptimization',
    type: 'hook',
    href: '/reference/hooks/use-token-optimization-enhanced',
    description: '',
    category: 'reference',
  },
  {
    title: 'useTokenTracker',
    type: 'hook',
    href: '/reference/hooks/use-token-tracker',
    description: '',
    category: 'reference',
  },
  {
    title: 'useVectorStore',
    type: 'hook',
    href: '/reference/hooks/use-vector-store',
    description: '',
    category: 'reference',
  },
  {
    title: 'useVoiceInput Hook',
    type: 'hook',
    href: '/reference/hooks/use-voice-input',
    description: '',
    category: 'reference',
  },
  {
    title: 'Which Hook Should I Use?',
    type: 'hook',
    href: '/reference/hooks/selector',
    description: '',
    category: 'reference',
  },
  {
    title: 'Advanced Tool Calling',
    type: 'example',
    href: '/examples/tool-calling-showcase',
    description: '',
    category: 'examples',
  },
  {
    title: 'AI Agents Workflow',
    type: 'example',
    href: '/examples/ai-agents-workflow',
    description: '',
    category: 'examples',
  },
  {
    title: 'Code Assistant',
    type: 'example',
    href: '/examples/code-assistant',
    description: '',
    category: 'examples',
  },
  {
    title: 'Conversation Branching',
    type: 'example',
    href: '/examples/conversation-branching',
    description: '',
    category: 'examples',
  },
  {
    title: 'Custom Styling',
    type: 'example',
    href: '/examples/custom-styling',
    description: '',
    category: 'examples',
  },
  {
    title: 'Document Summarizer',
    type: 'example',
    href: '/examples/document-summarizer',
    description: '',
    category: 'examples',
  },
  {
    title: 'Ecommerce Assistant',
    type: 'example',
    href: '/examples/ecommerce-assistant',
    description: '',
    category: 'examples',
  },
  {
    title: 'Education Tutor',
    type: 'example',
    href: '/examples/education-tutor',
    description: '',
    category: 'examples',
  },
  {
    title: 'Email Assistant',
    type: 'example',
    href: '/examples/email-assistant',
    description: '',
    category: 'examples',
  },
  {
    title: 'Examples',
    type: 'example',
    href: '/examples',
    description: '',
    category: 'examples',
  },
  {
    title: 'Financial Advisor',
    type: 'example',
    href: '/examples/financial-advisor',
    description: '',
    category: 'examples',
  },
  {
    title: 'Healthcare Assistant',
    type: 'example',
    href: '/examples/healthcare-assistant',
    description: '',
    category: 'examples',
  },
  {
    title: 'Hero Particles',
    type: 'example',
    href: '/examples/particles',
    description: '',
    category: 'examples',
  },
  {
    title: 'Model Switching Demo',
    type: 'example',
    href: '/examples/model-switching',
    description: '',
    category: 'examples',
  },
  {
    title: 'Multi-user Chat',
    type: 'example',
    href: '/examples/multi-user-chat',
    description: '',
    category: 'examples',
  },
  {
    title: 'Simple Chat Example',
    type: 'example',
    href: '/examples/simple-chat',
    description: '',
    category: 'examples',
  },
  {
    title: 'Streaming Chat Demo',
    type: 'example',
    href: '/examples/streaming',
    description: '',
    category: 'examples',
  },
  {
    title: 'The Hero Chat Experience',
    type: 'example',
    href: '/examples/hero-chat-demo',
    description: '',
    category: 'examples',
  },
  {
    title: 'Themed Chat Example',
    type: 'example',
    href: '/examples/themed-chat',
    description: '',
    category: 'examples',
  },
  {
    title: 'Token Optimization',
    type: 'example',
    href: '/examples/token-optimization',
    description: '',
    category: 'examples',
  },
  {
    title: 'Virtualized Chat Transcript',
    type: 'example',
    href: '/examples/virtualized-chat',
    description: '',
    category: 'examples',
  },
  {
    title: '3-Line Quick Start',
    type: 'cookbook',
    href: '/cookbook/quick-start-3-lines',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Accessibility Patterns',
    type: 'cookbook',
    href: '/cookbook/accessibility-patterns',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Advanced Agent Workflow',
    type: 'cookbook',
    href: '/cookbook/advanced-agent-workflow',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Advanced Export Workflows',
    type: 'cookbook',
    href: '/cookbook/advanced-export',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Advanced RAG Patterns',
    type: 'cookbook',
    href: '/cookbook/advanced-rag-patterns',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'AI Agent with Tools',
    type: 'cookbook',
    href: '/cookbook/agent-with-tools',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Analytics & Tracking',
    type: 'cookbook',
    href: '/cookbook/analytics-tracking',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Backend Integration Patterns',
    type: 'cookbook',
    href: '/cookbook/backend-integration-patterns',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Caching Strategies Recipe',
    type: 'cookbook',
    href: '/cookbook/caching-strategies',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Conversation Branching',
    type: 'cookbook',
    href: '/cookbook/conversation-branching',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Cookbook',
    type: 'cookbook',
    href: '/cookbook',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Custom Theming',
    type: 'cookbook',
    href: '/cookbook/custom-theming',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Custom Tool Integration Recipe',
    type: 'cookbook',
    href: '/cookbook/custom-tool-integration',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Enterprise SSO Setup',
    type: 'cookbook',
    href: '/cookbook/enterprise-sso-setup',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Error Handling Recipe',
    type: 'cookbook',
    href: '/cookbook/error-handling',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'LaTeX + Markdown Renderer',
    type: 'cookbook',
    href: '/cookbook/latex-markdown',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Memory Integration Recipe',
    type: 'cookbook',
    href: '/cookbook/memory-integration',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Multi-Agent Orchestration',
    type: 'cookbook',
    href: '/cookbook/multi-agent-orchestration',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Multi-Modal Chat Recipe',
    type: 'cookbook',
    href: '/cookbook/multi-modal-chat',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Multi-Tenant Chat',
    type: 'cookbook',
    href: '/cookbook/multi-tenant-chat',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Next.js Integration Deep Dive',
    type: 'cookbook',
    href: '/cookbook/nextjs-integration',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Offline-First Chat',
    type: 'cookbook',
    href: '/cookbook/offline-first-chat',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Offline-First Recipe',
    type: 'cookbook',
    href: '/cookbook/offline-first',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'OpenAI Streaming Chat',
    type: 'cookbook',
    href: '/cookbook/openai-streaming-chat',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Production Monitoring & Observability',
    type: 'cookbook',
    href: '/cookbook/production-monitoring',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Progressive Web App',
    type: 'cookbook',
    href: '/cookbook/progressive-web-app',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'RAG Document Chat',
    type: 'cookbook',
    href: '/cookbook/rag-document-chat',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Rate Limiting &amp; Quotas',
    type: 'cookbook',
    href: '/cookbook/rate-limiting',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Real-time Collaboration',
    type: 'cookbook',
    href: '/cookbook/real-time-collaboration',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Remix Integration',
    type: 'cookbook',
    href: '/cookbook/remix-integration',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Server-Side Rendering Patterns',
    type: 'cookbook',
    href: '/cookbook/server-side-rendering',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Streaming Chat with Memory',
    type: 'cookbook',
    href: '/cookbook/streaming-with-memory',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Streaming Setup Recipe',
    type: 'cookbook',
    href: '/cookbook/streaming-setup',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Team Collaboration Chat',
    type: 'cookbook',
    href: '/cookbook/team-collaboration-chat',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'User Authentication',
    type: 'cookbook',
    href: '/cookbook/authentication',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Vite Integration',
    type: 'cookbook',
    href: '/cookbook/vite-integration',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Voice Input Recipe',
    type: 'cookbook',
    href: '/cookbook/voice-input',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Voice-Enabled Chat',
    type: 'cookbook',
    href: '/cookbook/voice-chat',
    description: '',
    category: 'cookbook',
  },
  {
    title: 'Animations &amp; Motion',
    type: 'concept',
    href: '/learn/concepts/animations',
    description: '',
    category: 'learn',
  },
  {
    title: 'Component System',
    type: 'concept',
    href: '/learn/concepts/components',
    description: '',
    category: 'learn',
  },
  {
    title: 'Core Concepts',
    type: 'concept',
    href: '/learn/concepts',
    description: '',
    category: 'learn',
  },
  {
    title: 'React Hooks',
    type: 'concept',
    href: '/learn/concepts/hooks',
    description: '',
    category: 'learn',
  },
  {
    title: 'Theming System',
    type: 'concept',
    href: '/learn/concepts/theming',
    description: '',
    category: 'learn',
  },
  {
    title: 'Deploy to AWS',
    type: 'deployment',
    href: '/learn/deployment/aws',
    description: '',
    category: 'learn',
  },
  {
    title: 'Deploy to Vercel',
    type: 'deployment',
    href: '/learn/deployment/vercel',
    description: '',
    category: 'learn',
  },
  {
    title: 'Deployment Guides',
    type: 'deployment',
    href: '/learn/deployment',
    description: '',
    category: 'learn',
  },
  {
    title: 'Docker Deployment',
    type: 'deployment',
    href: '/learn/deployment/docker',
    description: '',
    category: 'learn',
  },
  {
    title: 'Next.js Integration',
    type: 'integration',
    href: '/integrations/nextjs',
    description: '',
    category: 'integrations',
  },
  {
    title: 'Remix Integration',
    type: 'integration',
    href: '/integrations/remix',
    description: '',
    category: 'integrations',
  },
  {
    title: 'Vite Integration',
    type: 'integration',
    href: '/integrations/vite',
    description: '',
    category: 'integrations',
  },
]
