import * as React from 'react'
import { motion } from 'framer-motion'
import {
  Badge,
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
  cn,
} from '@clarity-chat/primitives'
import { useReducedMotion } from '../../hooks/ui/use-reduced-motion'

export interface ResponseQualityMetric {
  id: string
  label: string
  score: number
  target?: number
  description?: string
}

export interface ResponseQualityMeterProps {
  metrics: ResponseQualityMetric[]
  overallLabel?: string
  overallScore?: number
  className?: string
  title?: string
  subtitle?: string
  scaleLabel?: string
}

const clampScore = (value: number) => Math.max(0, Math.min(1, value))

const defaultTitle = 'Response quality insights'
const defaultSubtitle =
  'Track groundedness, coverage, and other evaluation signals generated by your scoring pipeline.'

export const ResponseQualityMeter: React.FC<ResponseQualityMeterProps> = ({
  metrics,
  overallLabel = 'Overall score',
  overallScore,
  className,
  title = defaultTitle,
  subtitle = defaultSubtitle,
  scaleLabel = 'Confidence index',
}) => {
  const prefersReducedMotion = useReducedMotion()
  const normalizedMetrics = metrics.map((metric) => ({
    ...metric,
    score: clampScore(metric.score),
    target: metric.target !== undefined ? clampScore(metric.target) : undefined,
  }))

  const overall =
    overallScore !== undefined ? clampScore(overallScore) : undefined

  return (
    <Card className={cn('border-border/50 bg-background shadow-md', className)}>
      <CardHeader className="space-y-3">
        <div className="flex flex-col gap-1">
          <CardTitle className="text-lg font-semibold text-foreground">
            {title}
          </CardTitle>
          <CardDescription className="text-sm text-muted-foreground/80">
            {subtitle}
          </CardDescription>
        </div>
      </CardHeader>
      <CardContent className="space-y-6">
        {overall !== undefined && (
          <div className="flex flex-wrap items-center gap-3 rounded-lg border border-border/50 bg-muted px-4 py-3">
            <span className="text-sm font-semibold text-foreground">
              {overallLabel}
            </span>
            <div className="flex items-center gap-2 text-xs text-muted-foreground/70">
              <span>{Math.round(overall * 100)}%</span>
              <Badge
                variant={
                  overall >= 0.75
                    ? 'success'
                    : overall >= 0.5
                      ? 'warning'
                      : 'destructive'
                }
              >
                {overall >= 0.75
                  ? 'Excellent'
                  : overall >= 0.5
                    ? 'Needs review'
                    : 'Low confidence'}
              </Badge>
            </div>
          </div>
        )}

        <div className="space-y-4">
          {normalizedMetrics.map((metric) => (
            <div
              key={metric.id}
              className="space-y-2 rounded-lg border border-border/50 bg-muted p-4 shadow-md"
            >
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div className="flex flex-col">
                  <span className="text-sm font-semibold text-foreground">
                    {metric.label}
                  </span>
                  {metric.description && (
                    <span className="text-xs text-muted-foreground/70">
                      {metric.description}
                    </span>
                  )}
                </div>
                <span className="text-xs font-medium text-muted-foreground/70">
                  {Math.round(metric.score * 100)}%
                </span>
              </div>
              <div className="relative h-3 overflow-hidden rounded-full bg-background">
                {prefersReducedMotion ? (
                  <div
                    className="absolute inset-y-0 left-0 rounded-full bg-primary"
                    style={{ width: `${metric.score * 100}%` }}
                  />
                ) : (
                  <motion.div
                    className="absolute inset-y-0 left-0 rounded-full bg-primary"
                    initial={{ width: 0 }}
                    animate={{ width: `${metric.score * 100}%` }}
                    transition={{
                      // Framer Motion 12: Spring-based progress animation
                      type: 'spring',
                      damping: 25,
                      stiffness: 200,
                    }}
                    viewport={{ once: true }}
                  />
                )}
                {metric.target !== undefined && (
                  <span
                    className="absolute inset-y-0 w-[2px] bg-success"
                    style={{ left: `${metric.target * 100}%` }}
                  />
                )}
              </div>
              {metric.target !== undefined && (
                <span className="text-[11px] text-muted-foreground/60">
                  Target threshold {Math.round(metric.target * 100)}%
                </span>
              )}
            </div>
          ))}
        </div>

        <footer className="rounded-lg border border-dashed border-border/50 bg-muted px-4 py-3 text-xs text-muted-foreground/70">
          {scaleLabel}: 0-40% (low trust) · 40-75% (needs review) · 75-100%
          (ship with confidence)
        </footer>
      </CardContent>
    </Card>
  )
}

ResponseQualityMeter.displayName = 'ResponseQualityMeter'
