import type { Meta, StoryObj } from '@storybook/react-vite'
import { ResponseQualityMeter } from '@clarity-chat/react'
import type { ResponseQualityMetric } from '@clarity-chat/react'

const meta: Meta<typeof ResponseQualityMeter> = {
  title: 'Components/Feedback/ResponseQualityMeter',
  component: ResponseQualityMeter,
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component:
          'Track groundedness, coverage, and other evaluation signals generated by your scoring pipeline. Visual quality metrics with confidence indicators.',
      },
    },
    layout: 'padded',
  },
}

export default meta
type Story = StoryObj<typeof ResponseQualityMeter>

const mockMetrics: ResponseQualityMetric[] = [
  {
    id: '1',
    label: 'Groundedness',
    score: 0.85,
    target: 0.8,
    description: 'How well the response is supported by sources',
  },
  {
    id: '2',
    label: 'Coverage',
    score: 0.72,
    target: 0.75,
    description: 'Breadth of topics covered',
  },
  {
    id: '3',
    label: 'Relevance',
    score: 0.91,
    description: 'Relevance to the query',
  },
]

export const Default: Story = {
  args: {
    metrics: mockMetrics,
  },
}

export const WithOverallScore: Story = {
  args: {
    metrics: mockMetrics,
    overallScore: 0.83,
  },
}

export const AllQualityLevels: Story = {
  args: {
    metrics: [
      {
        id: '1',
        label: 'Excellent',
        score: 0.92,
        description: 'High quality response',
      },
      {
        id: '2',
        label: 'Good',
        score: 0.68,
        description: 'Meets expectations',
      },
      {
        id: '3',
        label: 'Needs Review',
        score: 0.45,
        description: 'Below target threshold',
      },
      {
        id: '4',
        label: 'Low Confidence',
        score: 0.25,
        description: 'Requires attention',
      },
    ],
    overallScore: 0.58,
  },
}

export const WithTargets: Story = {
  args: {
    metrics: [
      {
        id: '1',
        label: 'Above Target',
        score: 0.95,
        target: 0.8,
      },
      {
        id: '2',
        label: 'Below Target',
        score: 0.65,
        target: 0.75,
      },
      {
        id: '3',
        label: 'On Target',
        score: 0.80,
        target: 0.8,
      },
    ],
  },
}

export const CustomTitle: Story = {
  args: {
    metrics: mockMetrics,
    title: 'Components/Feedback/ResponseQualityMeter',
    subtitle: 'Components/Feedback/ResponseQualityMeter',
    overallLabel: 'Average Score',
    scaleLabel: 'Quality Index',
  },
}
