import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, CardDescription, cn, } from '@clarity-chat/primitives';
const statusBadge = {
    active: { label: 'Active', variant: 'success' },
    expired: { label: 'Expired', variant: 'warning' },
    revoked: { label: 'Revoked', variant: 'destructive' },
};
export const ApiTokenManager = ({ tokens, onCreate, onRegenerate, onRevoke, className, }) => {
    return (_jsxs(Card, { className: cn('border-border/60 bg-[hsl(var(--surface-elevated))] shadow-[0_24px_54px_rgba(15,23,42,0.18)]', className), children: [_jsxs(CardHeader, { className: "flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between", children: [_jsxs("div", { className: "space-y-1.5", children: [_jsx(CardTitle, { className: "text-lg font-semibold text-foreground", children: "API access tokens" }), _jsx(CardDescription, { className: "text-sm text-muted-foreground/80", children: "Rotate tokens regularly to maintain compliance and revoke unused credentials." })] }), _jsx(Button, { variant: "surface", onClick: onCreate, children: "Generate new token" })] }), _jsx(CardContent, { className: "overflow-x-auto", children: _jsxs("table", { className: "min-w-[720px] text-sm", children: [_jsx("thead", { className: "text-left text-xs uppercase tracking-wide text-muted-foreground/70", children: _jsxs("tr", { children: [_jsx("th", { className: "py-2", children: "Label" }), _jsx("th", { className: "py-2", children: "Scopes" }), _jsx("th", { className: "py-2", children: "Created" }), _jsx("th", { className: "py-2", children: "Last used" }), _jsx("th", { className: "py-2", children: "Status" }), _jsx("th", { className: "py-2", children: "Actions" })] }) }), _jsxs("tbody", { children: [tokens.map((token) => {
                                    const status = statusBadge[token.status];
                                    return (_jsxs("tr", { className: "border-t border-border/40 align-top", "data-status": token.status, children: [_jsx("td", { className: "px-2 py-3 font-medium text-foreground", children: token.label }), _jsx("td", { className: "px-2 py-3 text-xs text-muted-foreground/70", children: _jsx("div", { className: "flex flex-wrap gap-1", children: token.scopes.map((scope) => (_jsx(Badge, { variant: "outline", className: "text-[11px]", children: scope }, scope))) }) }), _jsx("td", { className: "px-2 py-3 text-xs text-muted-foreground/70", children: token.createdAt }), _jsx("td", { className: "px-2 py-3 text-xs text-muted-foreground/70", children: token.lastUsed ?? '—' }), _jsx("td", { className: "px-2 py-3", children: _jsx(Badge, { variant: status.variant, children: status.label }) }), _jsx("td", { className: "px-2 py-3", children: _jsxs("div", { className: "flex flex-wrap gap-2", children: [token.status === 'active' && (_jsx(Button, { variant: "ghost", size: "sm", onClick: () => onRegenerate?.(token), children: "Regenerate" })), _jsx(Button, { variant: "ghost", size: "sm", className: "text-destructive hover:text-destructive", onClick: () => onRevoke?.(token), children: "Revoke" })] }) })] }, token.id));
                                }), tokens.length === 0 && (_jsx("tr", { children: _jsx("td", { colSpan: 6, className: "px-2 py-6 text-center text-sm text-muted-foreground/80", children: "No tokens yet. Generate your first API token to integrate with the platform." }) }))] })] }) })] }));
};
ApiTokenManager.displayName = 'ApiTokenManager';
//# sourceMappingURL=ApiTokenManager.js.map