import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, CardDescription, Input, Textarea, cn, } from '@clarity-chat/primitives';
const statusBadge = {
    pending: { label: 'Pending', variant: 'info' },
    'in-progress': { label: 'In progress', variant: 'warning' },
    complete: { label: 'Complete', variant: 'success' },
};
export const SSOConfigWizard = ({ providerName = 'SAML 2.0', steps, metadata, notes, onNotesChange, onDownloadMetadata, onSubmit, className, }) => {
    return (_jsxs(Card, { className: cn('border-border/60 bg-[hsl(var(--surface-elevated))] shadow-md', className), children: [_jsxs(CardHeader, { className: "space-y-2", children: [_jsxs(CardTitle, { className: "text-lg font-semibold text-foreground", children: ["Configure ", providerName, " SSO"] }), _jsx(CardDescription, { className: "text-sm text-muted-foreground/80", children: "Follow the guided steps to connect your identity provider. Save changes once all steps are complete." })] }), _jsxs(CardContent, { className: "space-y-6", children: [_jsx("ol", { className: "space-y-4", children: steps.map((step, index) => (_jsxs("li", { className: "rounded-lg border border-border/50 bg-muted p-4", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-2", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("span", { className: "text-xs font-semibold uppercase tracking-wide text-muted-foreground/70", children: ["Step ", index + 1] }), _jsx("h3", { className: "text-sm font-semibold text-foreground", children: step.title })] }), step.status && (_jsx(Badge, { variant: statusBadge[step.status].variant, className: "uppercase", children: statusBadge[step.status].label }))] }), _jsx("p", { className: "mt-2 text-sm text-muted-foreground/80", children: step.description })] }, step.id))) }), metadata && (_jsxs("div", { className: "space-y-3 rounded-lg border border-border/50 bg-muted p-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h4", { className: "text-sm font-semibold text-foreground", children: "Service provider metadata" }), _jsx(Button, { variant: "ghost", size: "sm", onClick: onDownloadMetadata, children: "Download XML" })] }), _jsxs("div", { className: "grid gap-3 md:grid-cols-2", children: [_jsxs("label", { className: "text-xs font-medium uppercase tracking-wide text-muted-foreground/70", children: ["ACS URL", _jsx(Input, { value: metadata.acsUrl, readOnly: true, className: "mt-1 bg-background/70" })] }), _jsxs("label", { className: "text-xs font-medium uppercase tracking-wide text-muted-foreground/70", children: ["Entity ID", _jsx(Input, { value: metadata.entityId, readOnly: true, className: "mt-1 bg-background/70" })] })] })] })), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-xs font-medium uppercase tracking-wide text-muted-foreground/70", htmlFor: "sso-notes", children: "Internal notes" }), _jsx(Textarea, { id: "sso-notes", value: notes, onChange: (event) => onNotesChange?.(event.target.value), placeholder: "Record admin notes or escalation instructions...", className: "min-h-[120px] resize-y bg-background/60" })] }), _jsx("div", { className: "flex flex-wrap justify-end gap-2", children: _jsx(Button, { variant: "surface", onClick: onSubmit, children: "Save configuration" }) })] })] }));
};
SSOConfigWizard.displayName = 'SSOConfigWizard';
//# sourceMappingURL=SSOConfigWizard.js.map