import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import * as React from 'react';
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, CardDescription, Input, Textarea, cn, } from '@clarity-chat/primitives';
import { Skeleton } from '../ui/skeleton';
const statusBadge = {
    pending: { label: 'Pending', variant: 'info' },
    'in-progress': { label: 'In progress', variant: 'warning' },
    complete: { label: 'Complete', variant: 'success' },
};
const CopyIcon = () => (_jsx("svg", { className: "h-4 w-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", "aria-hidden": "true", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" }) }));
const CheckIcon = () => (_jsx("svg", { className: "h-4 w-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", "aria-hidden": "true", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M5 13l4 4L19 7" }) }));
const StepsSkeleton = () => (_jsx("ol", { className: "space-y-4", children: [1, 2, 3].map((i) => (_jsxs("li", { className: "rounded-lg border border-border/50 bg-muted p-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Skeleton, { width: 50, height: 14 }), _jsx(Skeleton, { width: 150, height: 16 })] }), _jsx(Skeleton, { width: 70, height: 20 })] }), _jsx("div", { className: "mt-2", children: _jsx(Skeleton, { width: "90%", height: 14 }) })] }, i))) }));
const CopyableInput = ({ label, value, id }) => {
    const [copied, setCopied] = React.useState(false);
    const handleCopy = async () => {
        try {
            await navigator.clipboard.writeText(value);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        }
        catch (err) {
            console.error('Failed to copy:', err);
        }
    };
    return (_jsxs("div", { className: "space-y-1", children: [_jsx("label", { htmlFor: id, className: "text-xs font-medium uppercase tracking-wide text-muted-foreground/70", children: label }), _jsxs("div", { className: "relative", children: [_jsx(Input, { id: id, value: value, readOnly: true, className: "bg-background/70 pr-10" }), _jsx(Button, { type: "button", variant: "ghost", size: "sm", className: "absolute right-1 top-1/2 h-7 w-7 -translate-y-1/2 p-0", onClick: handleCopy, "aria-label": copied ? 'Copied!' : `Copy ${label}`, children: copied ? _jsx(CheckIcon, {}) : _jsx(CopyIcon, {}) })] })] }));
};
export const SSOConfigWizard = ({ providerName = 'SAML 2.0', steps, metadata, notes, onNotesChange, onDownloadMetadata, onTestConnection, onSubmit, onStepHelp, isLoading = false, isProcessing = false, isTesting = false, testResult, className, }) => {
    // Calculate progress
    const completedSteps = steps.filter((s) => s.status === 'complete').length;
    const totalSteps = steps.length;
    const progress = totalSteps > 0 ? (completedSteps / totalSteps) * 100 : 0;
    const allComplete = completedSteps === totalSteps && totalSteps > 0;
    return (_jsxs(Card, { className: cn('border-border/60 bg-[hsl(var(--surface-elevated))] shadow-md', className), "aria-busy": isLoading || isProcessing, children: [_jsxs(CardHeader, { className: "space-y-2", children: [_jsxs("div", { className: "flex items-start justify-between gap-4", children: [_jsx("div", { className: "space-y-1", children: isLoading ? (_jsxs(_Fragment, { children: [_jsx(Skeleton, { width: 200, height: 24 }), _jsx(Skeleton, { width: 280, height: 14 })] })) : (_jsxs(_Fragment, { children: [_jsxs(CardTitle, { className: "text-lg font-semibold text-foreground", children: ["Configure ", providerName, " SSO"] }), _jsx(CardDescription, { className: "text-sm text-muted-foreground/80", children: "Follow the guided steps to connect your identity provider. Save changes once all steps are complete." })] })) }), !isLoading && totalSteps > 0 && (_jsxs(Badge, { variant: allComplete ? 'success' : 'info', className: "whitespace-nowrap", children: [completedSteps, "/", totalSteps, " complete"] }))] }), !isLoading && totalSteps > 0 && (_jsx("div", { className: "pt-2", children: _jsx("div", { role: "progressbar", "aria-label": "Configuration progress", "aria-valuemin": 0, "aria-valuemax": 100, "aria-valuenow": Math.round(progress), className: "h-1.5 w-full overflow-hidden rounded-full bg-muted", children: _jsx("div", { className: cn('h-full rounded-full transition-all duration-300', allComplete ? 'bg-success' : 'bg-primary'), style: { width: `${progress}%` } }) }) }))] }), _jsxs(CardContent, { className: "space-y-6", children: [isLoading ? (_jsx(StepsSkeleton, {})) : (_jsx("ol", { className: "space-y-4", role: "list", "aria-label": "Configuration steps", children: steps.map((step, index) => {
                            const status = step.status ?? 'pending';
                            const isComplete = status === 'complete';
                            const isInProgress = status === 'in-progress';
                            return (_jsxs("li", { className: cn('rounded-lg border p-4 transition-colors', isComplete
                                    ? 'border-success/50 bg-success/5'
                                    : isInProgress
                                        ? 'border-warning/50 bg-warning/5'
                                        : 'border-border/50 bg-muted'), children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-2", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: cn('flex h-6 w-6 items-center justify-center rounded-full text-xs font-semibold', isComplete
                                                            ? 'bg-success text-success-foreground'
                                                            : isInProgress
                                                                ? 'bg-warning text-warning-foreground'
                                                                : 'bg-muted-foreground/20 text-muted-foreground'), children: isComplete ? (_jsx("svg", { className: "h-3.5 w-3.5", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 3, d: "M5 13l4 4L19 7" }) })) : (index + 1) }), _jsx("h3", { className: "text-sm font-semibold text-foreground", children: step.title })] }), _jsxs("div", { className: "flex items-center gap-2", children: [step.helpUrl && onStepHelp && (_jsx(Button, { variant: "ghost", size: "sm", className: "h-6 text-xs", onClick: () => onStepHelp(step), children: "Help" })), _jsx(Badge, { variant: statusBadge[status].variant, className: "uppercase", children: statusBadge[status].label })] })] }), _jsx("p", { className: "mt-2 text-sm text-muted-foreground/80", children: step.description })] }, step.id));
                        }) })), metadata && (_jsxs("div", { className: "space-y-3 rounded-lg border border-border/50 bg-muted p-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h4", { className: "text-sm font-semibold text-foreground", children: "Service provider metadata" }), _jsxs(Button, { variant: "ghost", size: "sm", onClick: onDownloadMetadata, disabled: isProcessing, children: [_jsx("svg", { className: "mr-1.5 h-4 w-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", "aria-hidden": "true", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" }) }), "Download XML"] })] }), _jsxs("div", { className: "grid gap-3 md:grid-cols-2", children: [_jsx(CopyableInput, { label: "ACS URL", value: metadata.acsUrl, id: "sso-acs-url" }), _jsx(CopyableInput, { label: "Entity ID", value: metadata.entityId, id: "sso-entity-id" })] })] })), onTestConnection && (_jsxs("div", { className: "space-y-3 rounded-lg border border-border/50 bg-muted p-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h4", { className: "text-sm font-semibold text-foreground", children: "Test connection" }), _jsx("p", { className: "text-xs text-muted-foreground/70", children: "Verify your SSO configuration before saving" })] }), _jsx(Button, { variant: "surface", size: "sm", onClick: onTestConnection, disabled: isProcessing || isTesting, children: isTesting ? (_jsxs(_Fragment, { children: [_jsxs("svg", { className: "mr-1.5 h-4 w-4 animate-spin", fill: "none", viewBox: "0 0 24 24", "aria-hidden": "true", children: [_jsx("circle", { className: "opacity-25", cx: "12", cy: "12", r: "10", stroke: "currentColor", strokeWidth: "4" }), _jsx("path", { className: "opacity-75", fill: "currentColor", d: "M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" })] }), "Testing..."] })) : ('Test connection') })] }), testResult && (_jsx("div", { className: cn('rounded-md p-3 text-sm', testResult.success
                                    ? 'bg-success/10 text-success'
                                    : 'bg-destructive/10 text-destructive'), role: "alert", children: _jsxs("div", { className: "flex items-center gap-2", children: [testResult.success ? (_jsx("svg", { className: "h-4 w-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", "aria-hidden": "true", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" }) })) : (_jsx("svg", { className: "h-4 w-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", "aria-hidden": "true", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" }) })), _jsx("span", { children: testResult.message })] }) }))] })), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-xs font-medium uppercase tracking-wide text-muted-foreground/70", htmlFor: "sso-notes", children: "Internal notes" }), _jsx(Textarea, { id: "sso-notes", value: notes, onChange: (event) => onNotesChange?.(event.target.value), placeholder: "Record admin notes or escalation instructions...", className: "min-h-[120px] resize-y bg-background/60", disabled: isProcessing })] }), _jsx("div", { className: "flex flex-wrap justify-end gap-2", children: _jsx(Button, { variant: "surface", onClick: onSubmit, disabled: isProcessing, children: isProcessing ? 'Saving...' : 'Save configuration' }) })] })] }));
};
SSOConfigWizard.displayName = 'SSOConfigWizard';
//# sourceMappingURL=SSOConfigWizard.js.map