'use client'

import { useState, useCallback, useRef, useEffect } from 'react'
import { StreamingMessage } from '@clarity-chat/react'
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
  Button,
  Badge,
  cn,
  Separator,
} from '@clarity-chat/primitives'
import {
  Play,
  Square,
  RotateCw,
  Zap,
  Activity,
  Clock,
  AlertCircle,
  CheckCircle,
  Wifi,
  WifiOff,
  TrendingUp,
  Loader2,
  Brain,
} from 'lucide-react'

// ============================================================================
// INLINE COMPONENTS
// ============================================================================

// Simple inline ThinkingIndicator
function SimpleThinkingIndicator({ message }: { message: string }) {
  return (
    <div className="flex items-center gap-3 p-4 rounded-lg border border-blue-500/30 bg-blue-500/10">
      <Brain className="h-5 w-5 text-blue-500 animate-pulse" />
      <div className="flex-1">
        <p className="text-sm font-medium text-blue-600">Thinking...</p>
        <p className="text-xs text-muted-foreground mt-0.5">{message}</p>
      </div>
    </div>
  )
}

// Simple inline StreamCancellation
function SimpleStreamCancellation({ onCancel }: { onCancel: () => void }) {
  return (
    <Button onClick={onCancel} variant="outline" size="sm" className="gap-2">
      <Square className="h-4 w-4" />
      Stop Generation
    </Button>
  )
}

// ============================================================================
// TYPES
// ============================================================================

interface StreamMessage {
  id: string
  content: string
  isComplete: boolean
  timestamp: Date
  tokenCount: number
  thinkingSteps?: string[]
  error?: string
}

type StreamStatus = 'idle' | 'streaming' | 'paused' | 'completed' | 'error'
type ConnectionStatus = 'connected' | 'disconnected' | 'reconnecting'

// ============================================================================
// MOCK SSE SIMULATION
// ============================================================================

const SAMPLE_RESPONSES = [
  {
    content: `Let me explain how Server-Sent Events (SSE) work in a streaming chat application.

**What is SSE?**
Server-Sent Events is a web technology that allows a server to push real-time updates to the client over a single HTTP connection. Unlike WebSockets, SSE is unidirectional (server to client only) and works over standard HTTP.

**Key Benefits:**
1. **Automatic Reconnection**: Built-in reconnection with exponential backoff
2. **Event ID Tracking**: Resume from where you left off after disconnection
3. **Simple Protocol**: Text-based format that's easy to debug
4. **Wide Browser Support**: Works in all modern browsers

**How It Works:**
When you send a message, the server opens a persistent connection and streams tokens back as they're generated by the AI model. Each token arrives as a separate event, allowing for smooth, real-time rendering.

This creates a natural, conversational feel where users see responses appear gradually, just like watching someone type.`,
    tokens: 180,
    thinkingSteps: [
      'Understanding the question about SSE streaming',
      'Retrieving documentation about Server-Sent Events',
      'Structuring the explanation with examples',
      'Preparing detailed response about benefits',
    ],
  },
  {
    content: `Here's a practical example of implementing SSE streaming in Next.js:

\`\`\`typescript
// API Route: app/api/chat/stream/route.ts
export async function POST(req: Request) {
  const encoder = new TextEncoder()

  const stream = new ReadableStream({
    async start(controller) {
      // Send thinking indicator
      controller.enqueue(encoder.encode('event: thinking\\n'))
      controller.enqueue(encoder.encode('data: Analyzing request...\\n\\n'))

      // Stream tokens
      const tokens = await generateResponse(prompt)
      for (const token of tokens) {
        controller.enqueue(encoder.encode(\`data: \${token}\\n\\n\`))
      }

      // Send completion
      controller.enqueue(encoder.encode('event: done\\n'))
      controller.enqueue(encoder.encode('data: [DONE]\\n\\n'))
      controller.close()
    }
  })

  return new Response(stream, {
    headers: {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      'Connection': 'keep-alive'
    }
  })
}
\`\`\`

This demonstrates the complete flow from request to streaming response!`,
    tokens: 220,
    thinkingSteps: [
      'Formulating code example for SSE',
      'Including Next.js API route structure',
      'Adding proper event types and headers',
    ],
  },
  {
    content: `Let me show you error handling and reconnection strategies:

**Error Scenarios to Handle:**
1. **Network Interruption**: Client loses internet connection
2. **Server Timeout**: Request takes too long to complete
3. **Rate Limiting**: Too many requests from the client
4. **Server Error**: 5xx response codes

**Reconnection Strategy:**
\`\`\`typescript
const reconnectConfig = {
  maxAttempts: 5,
  initialDelay: 1000,      // 1 second
  maxDelay: 30000,         // 30 seconds
  backoffMultiplier: 2,    // Exponential backoff
  jitter: 0.3              // ±30% randomization
}

function calculateDelay(attempt: number): number {
  const base = initialDelay * Math.pow(backoffMultiplier, attempt)
  const jitterRange = base * jitter
  const randomJitter = (Math.random() - 0.5) * 2 * jitterRange
  return Math.min(base + randomJitter, maxDelay)
}
\`\`\`

**Best Practices:**
- Use exponential backoff to avoid overwhelming the server
- Add jitter to prevent thundering herd problem
- Track Last-Event-ID for resumption
- Implement heartbeat to detect stale connections
- Provide user feedback during reconnection

This ensures a robust, production-ready streaming experience!`,
    tokens: 280,
    thinkingSteps: [
      'Analyzing error handling requirements',
      'Designing reconnection strategy',
      'Adding production best practices',
      'Completing comprehensive answer',
    ],
  },
]

// ============================================================================
// STREAMING MESSAGE DEMO COMPONENT
// ============================================================================

export function StreamingMessageDemo() {
  // State
  const [messages, setMessages] = useState<StreamMessage[]>([])
  const [currentMessage, setCurrentMessage] = useState<StreamMessage | null>(
    null
  )
  const [streamStatus, setStreamStatus] = useState<StreamStatus>('idle')
  const [connectionStatus, setConnectionStatus] =
    useState<ConnectionStatus>('connected')
  const [totalTokens, setTotalTokens] = useState(0)
  const [streamingSpeed, setStreamingSpeed] = useState(50) // tokens per second
  const [reconnectAttempts, setReconnectAttempts] = useState(0)
  const [currentThinkingStep, setCurrentThinkingStep] = useState<
    string | undefined
  >()

  // Refs
  const streamControllerRef = useRef<AbortController | null>(null)
  const messageIndexRef = useRef(0)
  const tokenIndexRef = useRef(0)
  const animationFrameRef = useRef<number | null>(null)
  const lastUpdateRef = useRef<number>(0)

  // ============================================================================
  // STREAMING LOGIC
  // ============================================================================

  const simulateTokenStreaming = useCallback(() => {
    const sampleResponse = SAMPLE_RESPONSES[messageIndexRef.current]
    if (!sampleResponse) {
      messageIndexRef.current = 0
      return
    }

    const tokens = sampleResponse.content.split('')
    const totalTokenCount = tokens.length
    const messageId = `msg-${Date.now()}`

    // Initialize message
    const newMessage: StreamMessage = {
      id: messageId,
      content: '',
      isComplete: false,
      timestamp: new Date(),
      tokenCount: 0,
      thinkingSteps: sampleResponse.thinkingSteps,
    }

    setCurrentMessage(newMessage)
    setStreamStatus('streaming')
    tokenIndexRef.current = 0

    // Simulate thinking phase
    const thinkingSteps = sampleResponse.thinkingSteps || []
    let currentThinkingIndex = 0

    const thinkingInterval = setInterval(() => {
      if (currentThinkingIndex < thinkingSteps.length) {
        setCurrentThinkingStep(thinkingSteps[currentThinkingIndex])
        currentThinkingIndex++
      } else {
        clearInterval(thinkingInterval)
        setCurrentThinkingStep(undefined)
        startTokenStream()
      }
    }, 800)

    const startTokenStream = () => {
      const msPerToken = 1000 / streamingSpeed
      let lastTime = performance.now()

      const streamTokens = (currentTime: number) => {
        if (streamStatus === 'paused' || !streamControllerRef.current) {
          return
        }

        const elapsed = currentTime - lastTime

        if (elapsed >= msPerToken) {
          lastTime = currentTime

          if (tokenIndexRef.current < totalTokenCount) {
            const token = tokens[tokenIndexRef.current]
            tokenIndexRef.current++

            setCurrentMessage((prev) => {
              if (!prev) return null
              const updatedContent = prev.content + token
              const updatedTokens = prev.tokenCount + 1

              return {
                ...prev,
                content: updatedContent,
                tokenCount: updatedTokens,
              }
            })

            setTotalTokens((prev) => prev + 1)

            // Simulate occasional network issues
            if (Math.random() < 0.001) {
              // 0.1% chance of error
              simulateError()
              return
            }

            // Continue streaming
            animationFrameRef.current = requestAnimationFrame(streamTokens)
          } else {
            // Stream complete
            completeStream(newMessage)
          }
        } else {
          animationFrameRef.current = requestAnimationFrame(streamTokens)
        }
      }

      animationFrameRef.current = requestAnimationFrame(streamTokens)
    }
  }, [streamingSpeed, streamStatus])

  const completeStream = useCallback((message: StreamMessage) => {
    setCurrentMessage(null)
    setMessages((prev) => [
      ...prev,
      { ...message, content: message.content, isComplete: true },
    ])
    setStreamStatus('completed')
    setCurrentThinkingStep(undefined)

    // Move to next message for next stream
    messageIndexRef.current =
      (messageIndexRef.current + 1) % SAMPLE_RESPONSES.length
  }, [])

  const simulateError = useCallback(() => {
    setStreamStatus('error')
    setConnectionStatus('reconnecting')

    const errorMessage: StreamMessage = {
      id: `error-${Date.now()}`,
      content: currentMessage?.content || '',
      isComplete: false,
      timestamp: new Date(),
      tokenCount: currentMessage?.tokenCount || 0,
      error: 'Connection interrupted. Attempting to reconnect...',
    }

    setCurrentMessage(errorMessage)

    // Simulate reconnection
    setTimeout(() => {
      setReconnectAttempts((prev) => prev + 1)
      setConnectionStatus('connected')
      setStreamStatus('streaming')

      // Resume streaming
      if (currentMessage) {
        setCurrentMessage((prev) =>
          prev ? { ...prev, error: undefined } : null
        )
      }
    }, 2000)
  }, [currentMessage])

  // ============================================================================
  // ACTIONS
  // ============================================================================

  const handleStart = useCallback(() => {
    if (streamStatus === 'streaming') return

    streamControllerRef.current = new AbortController()
    simulateTokenStreaming()
  }, [streamStatus, simulateTokenStreaming])

  const handleStop = useCallback(() => {
    if (streamControllerRef.current) {
      streamControllerRef.current.abort()
      streamControllerRef.current = null
    }

    if (animationFrameRef.current) {
      cancelAnimationFrame(animationFrameRef.current)
      animationFrameRef.current = null
    }

    if (currentMessage && !currentMessage.isComplete) {
      setMessages((prev) => [
        ...prev,
        { ...currentMessage, isComplete: true },
      ])
      setCurrentMessage(null)
    }

    setStreamStatus('idle')
    setCurrentThinkingStep(undefined)
  }, [currentMessage])

  const handleRetry = useCallback(() => {
    setStreamStatus('idle')
    setCurrentMessage(null)
    setTimeout(() => handleStart(), 100)
  }, [handleStart])

  const handleReset = useCallback(() => {
    handleStop()
    setMessages([])
    setTotalTokens(0)
    setReconnectAttempts(0)
    messageIndexRef.current = 0
    tokenIndexRef.current = 0
  }, [handleStop])

  // Cleanup
  useEffect(() => {
    return () => {
      if (animationFrameRef.current) {
        cancelAnimationFrame(animationFrameRef.current)
      }
    }
  }, [])

  // ============================================================================
  // RENDER
  // ============================================================================

  const isStreaming = streamStatus === 'streaming'
  const isError = streamStatus === 'error'

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      {/* Main Streaming Display */}
      <Card className="lg:col-span-2 glass-card border-0 overflow-hidden">
        <CardHeader className="border-b border-white/10 bg-white/5">
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <Activity className="h-5 w-5 text-primary" />
                SSE Streaming Demo
              </CardTitle>
              <CardDescription className="mt-1">
                Token-by-token streaming with real-time updates
              </CardDescription>
            </div>
            <Badge
              variant={
                isStreaming
                  ? 'default'
                  : isError
                    ? 'destructive'
                    : 'secondary'
              }
              className="gap-1.5"
            >
              {connectionStatus === 'connected' && (
                <Wifi className="h-3 w-3" />
              )}
              {connectionStatus === 'disconnected' && (
                <WifiOff className="h-3 w-3" />
              )}
              {connectionStatus === 'reconnecting' && (
                <Loader2 className="h-3 w-3 animate-spin" />
              )}
              {connectionStatus === 'reconnecting'
                ? 'Reconnecting'
                : streamStatus.charAt(0).toUpperCase() + streamStatus.slice(1)}
            </Badge>
          </div>
        </CardHeader>

        <CardContent className="p-6">
          {/* Controls */}
          <div className="flex items-center gap-3 mb-6">
            <Button
              onClick={handleStart}
              disabled={isStreaming}
              className="gap-2"
            >
              <Play className="h-4 w-4" />
              Start Stream
            </Button>
            <Button
              onClick={handleStop}
              disabled={!isStreaming}
              variant="destructive"
              className="gap-2"
            >
              <Square className="h-4 w-4" />
              Stop
            </Button>
            <Button onClick={handleReset} variant="outline" className="gap-2">
              <RotateCw className="h-4 w-4" />
              Reset
            </Button>

            <div className="flex-1" />

            {isStreaming && <SimpleStreamCancellation onCancel={handleStop} />}
          </div>

          {/* Streaming Speed Control */}
          <div className="mb-6 p-4 rounded-lg bg-muted/30 border border-white/10">
            <div className="flex items-center justify-between mb-2">
              <label className="text-sm font-medium">
                Streaming Speed: {streamingSpeed} tokens/sec
              </label>
              <Badge variant="outline">{streamingSpeed * 60} tokens/min</Badge>
            </div>
            <input
              type="range"
              min="10"
              max="200"
              step="10"
              value={streamingSpeed}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                setStreamingSpeed(Number(e.target.value))
              }
              disabled={isStreaming}
              className="w-full h-2 bg-white/10 rounded-lg appearance-none cursor-pointer accent-primary"
            />
            <div className="flex justify-between text-xs text-muted-foreground mt-1">
              <span>Slow</span>
              <span>Fast</span>
            </div>
          </div>

          <Separator className="mb-6" />

          {/* Messages Display */}
          <div className="space-y-6 max-h-[600px] overflow-y-auto scrollbar-hide">
            {messages.map((message) => (
              <div key={message.id} className="space-y-2">
                <div className="flex items-center gap-2 text-xs text-muted-foreground">
                  <Clock className="h-3 w-3" />
                  {message.timestamp.toLocaleTimeString()}
                  <Badge variant="outline" className="text-xs">
                    {message.tokenCount} tokens
                  </Badge>
                  {message.isComplete && (
                    <CheckCircle className="h-3 w-3 text-green-500" />
                  )}
                </div>
                <StreamingMessage
                  content={message.content}
                  isStreaming={false}
                  smoothStreaming={false}
                  currentThinkingStep={undefined}
                  error={undefined}
                  onToolApprove={() => {}}
                  onToolReject={() => {}}
                  onRetry={() => {}}
                  className="prose prose-sm dark:prose-invert max-w-none"
                />
              </div>
            ))}

            {/* Current Streaming Message */}
            {currentMessage && (
              <div className="space-y-4">
                <div className="flex items-center gap-2 text-xs text-muted-foreground">
                  <Clock className="h-3 w-3" />
                  {currentMessage.timestamp.toLocaleTimeString()}
                  <Badge variant="outline" className="text-xs">
                    {currentMessage.tokenCount} tokens
                  </Badge>
                  {isStreaming && <Loader2 className="h-3 w-3 animate-spin" />}
                </div>

                {/* Thinking Indicator */}
                {currentThinkingStep && (
                  <SimpleThinkingIndicator message={currentThinkingStep} />
                )}

                {/* Streaming Content */}
                <StreamingMessage
                  content={currentMessage.content}
                  isStreaming={isStreaming}
                  error={currentMessage.error}
                  currentThinkingStep={currentThinkingStep}
                  onRetry={handleRetry}
                  onToolApprove={() => {}}
                  onToolReject={() => {}}
                  smoothStreaming={true}
                  streamingSpeed="normal"
                  className="prose prose-sm dark:prose-invert max-w-none"
                />
              </div>
            )}

            {/* Empty State */}
            {messages.length === 0 && !currentMessage && (
              <div className="text-center py-12 text-muted-foreground">
                <Activity className="h-12 w-12 mx-auto mb-3 opacity-50" />
                <p className="text-sm">
                  Click "Start Stream" to begin demonstration
                </p>
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Stats & Info Sidebar */}
      <div className="space-y-4">
        {/* Token Statistics */}
        <Card className="glass-card border-0">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm flex items-center gap-2">
              <TrendingUp className="h-4 w-4 text-primary" />
              Token Statistics
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="flex justify-between items-center">
              <span className="text-sm text-muted-foreground">
                Total Tokens
              </span>
              <Badge variant="secondary" className="font-mono">
                {totalTokens}
              </Badge>
            </div>
            <Separator />
            <div className="flex justify-between items-center">
              <span className="text-sm text-muted-foreground">
                Current Message
              </span>
              <Badge variant="secondary" className="font-mono">
                {currentMessage?.tokenCount || 0}
              </Badge>
            </div>
            <Separator />
            <div className="flex justify-between items-center">
              <span className="text-sm text-muted-foreground">
                Messages Sent
              </span>
              <Badge variant="secondary" className="font-mono">
                {messages.length}
              </Badge>
            </div>
            <Separator />
            <div className="flex justify-between items-center">
              <span className="text-sm text-muted-foreground">
                Reconnections
              </span>
              <Badge
                variant={reconnectAttempts > 0 ? 'destructive' : 'secondary'}
                className="font-mono"
              >
                {reconnectAttempts}
              </Badge>
            </div>
          </CardContent>
        </Card>

        {/* Connection Status */}
        <Card className="glass-card border-0">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm flex items-center gap-2">
              {connectionStatus === 'connected' && (
                <Wifi className="h-4 w-4 text-green-500" />
              )}
              {connectionStatus === 'disconnected' && (
                <WifiOff className="h-4 w-4 text-red-500" />
              )}
              {connectionStatus === 'reconnecting' && (
                <Loader2 className="h-4 w-4 text-yellow-500 animate-spin" />
              )}
              Connection Status
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div
              className={cn(
                'p-3 rounded-lg border',
                connectionStatus === 'connected' &&
                  'bg-green-500/10 border-green-500/30',
                connectionStatus === 'disconnected' &&
                  'bg-red-500/10 border-red-500/30',
                connectionStatus === 'reconnecting' &&
                  'bg-yellow-500/10 border-yellow-500/30'
              )}
            >
              <p className="text-sm font-medium">
                {connectionStatus === 'connected' && 'Connected'}
                {connectionStatus === 'disconnected' && 'Disconnected'}
                {connectionStatus === 'reconnecting' &&
                  'Reconnecting with exponential backoff...'}
              </p>
              {connectionStatus === 'reconnecting' && (
                <p className="text-xs text-muted-foreground mt-1">
                  Attempt {reconnectAttempts} - Using exponential backoff with
                  jitter
                </p>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Features */}
        <Card className="glass-card border-0">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm flex items-center gap-2">
              <Zap className="h-4 w-4 text-primary" />
              Features Demonstrated
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            {[
              'Token-by-token streaming',
              'Stop generation button',
              'Thinking indicators',
              'Real-time token counting',
              'Multiple message streaming',
              'Error handling during stream',
              'Automatic reconnection',
              'Exponential backoff',
              'Smooth streaming animation',
            ].map((feature, i) => (
              <div key={i} className="flex items-center gap-2 text-sm">
                <CheckCircle className="h-3.5 w-3.5 text-green-500" />
                <span>{feature}</span>
              </div>
            ))}
          </CardContent>
        </Card>

        {/* Info */}
        <Card className="glass-card border-0">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm flex items-center gap-2">
              <AlertCircle className="h-4 w-4 text-blue-500" />
              About This Demo
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-xs text-muted-foreground leading-relaxed">
              This demo simulates Server-Sent Events (SSE) streaming with
              automatic reconnection, error handling, and token counting. In
              production, use the <code>useStreamingSSE</code> hook with your
              API endpoint.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
