import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge, Card, CardContent, CardHeader, CardTitle, CardDescription, cn, } from '@clarity-chat/primitives';
import { ResponseQualityMeter } from '../response-quality-meter';
const trendCopy = {
    up: 'Improving',
    down: 'Regression',
    flat: 'Stable',
};
export const EvaluationDashboard = ({ metrics, sparklines = [], quality, className, }) => {
    return (_jsxs("div", { className: cn('grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(0,3fr)]', className), children: [_jsxs(Card, { className: "border-border/60 bg-[hsl(var(--surface-elevated))] shadow-[0_18px_42px_rgba(15,23,42,0.16)]", children: [_jsxs(CardHeader, { className: "space-y-2", children: [_jsx(CardTitle, { className: "text-lg font-semibold text-foreground", children: "Evaluation snapshot" }), _jsx(CardDescription, { className: "text-sm text-muted-foreground/80", children: "Live metrics from the latest prompt release." })] }), _jsx(CardContent, { className: "grid gap-4 sm:grid-cols-2", children: metrics.map((metric) => (_jsxs("div", { className: "rounded-2xl border border-border/40 bg-[hsl(var(--surface-muted))] p-4", children: [_jsx("p", { className: "text-xs font-semibold uppercase tracking-wide text-muted-foreground/70", children: metric.label }), _jsxs("div", { className: "mt-1 flex items-baseline gap-2", children: [_jsx("span", { className: "text-2xl font-semibold text-foreground", children: metric.value }), metric.trend && metric.change && (_jsxs(Badge, { variant: metric.trend === 'down' ? 'destructive' : metric.trend === 'up' ? 'success' : 'info', children: [trendCopy[metric.trend], " ", metric.change] }))] })] }, metric.id))) })] }), _jsxs("div", { className: "space-y-6", children: [quality && (_jsx(ResponseQualityMeter, { ...quality, className: "border-border/60 bg-[hsl(var(--surface-elevated))] shadow-[0_18px_42px_rgba(15,23,42,0.16)]" })), sparklines.length > 0 && (_jsxs(Card, { className: "border-border/60 bg-[hsl(var(--surface-elevated))] shadow-[0_18px_42px_rgba(15,23,42,0.16)]", children: [_jsxs(CardHeader, { className: "space-y-2", children: [_jsx(CardTitle, { className: "text-lg font-semibold text-foreground", children: "Cost & latency trends" }), _jsx(CardDescription, { className: "text-sm text-muted-foreground/80", children: "Track performance indicators against team objectives." })] }), _jsx(CardContent, { className: "space-y-4", children: sparklines.map((sparkline) => (_jsxs("div", { children: [_jsxs("div", { className: "flex items-center justify-between text-xs text-muted-foreground/70", children: [_jsx("span", { children: sparkline.label }), _jsxs("span", { children: [Math.round(sparkline.percentage), "%"] })] }), _jsx("div", { "aria-label": sparkline.label, role: "progressbar", "aria-valuemin": 0, "aria-valuemax": 100, "aria-valuenow": Math.round(sparkline.percentage), className: "mt-2 h-2 w-full overflow-hidden rounded-full bg-background", children: _jsx("div", { className: "h-full rounded-full bg-primary", style: { width: `${Math.min(100, Math.max(0, sparkline.percentage))}%` } }) }), sparkline.objective !== undefined && (_jsxs("div", { className: "mt-1 text-xs text-muted-foreground/60", children: ["Target ", sparkline.objective, "%"] }))] }, sparkline.id))) })] }))] })] }));
};
EvaluationDashboard.displayName = 'EvaluationDashboard';
//# sourceMappingURL=EvaluationDashboard.js.map