import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import * as React from 'react';
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, CardDescription, cn, } from '@clarity-chat/primitives';
import { ResponseQualityMeter, } from '../dashboards/response-quality-meter';
import { Skeleton } from '../ui/skeleton';
const trendCopy = {
    up: 'Improving',
    down: 'Regression',
    flat: 'Stable',
};
const MetricSkeleton = () => (_jsxs("div", { className: "rounded-2xl border border-border/40 bg-[hsl(var(--surface-muted))] p-4", children: [_jsx(Skeleton, { width: "60%", height: 12, className: "mb-2" }), _jsx(Skeleton, { width: "80%", height: 28 })] }));
const SparklineSkeleton = () => (_jsxs("div", { children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx(Skeleton, { width: "40%", height: 12 }), _jsx(Skeleton, { width: 32, height: 12 })] }), _jsx(Skeleton, { width: "100%", height: 8, className: "mt-2", rounded: "full" })] }));
const EmptyState = ({ message, onRefresh, }) => (_jsxs("div", { className: "flex flex-col items-center justify-center py-8 text-center", children: [_jsx("div", { className: "mb-3 rounded-full bg-muted p-3", children: _jsx("svg", { className: "h-6 w-6 text-muted-foreground", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", "aria-hidden": "true", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 1.5, d: "M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" }) }) }), _jsx("p", { className: "text-sm text-muted-foreground", children: message }), onRefresh && (_jsx(Button, { variant: "ghost", size: "sm", className: "mt-3", onClick: onRefresh, children: "Refresh data" }))] }));
export const EvaluationDashboard = ({ metrics, sparklines = [], quality, isLoading = false, emptyMessage = 'No evaluation metrics available. Run an evaluation to see results.', onRefresh, className, }) => {
    const hasMetrics = metrics.length > 0;
    const hasSparklines = sparklines.length > 0;
    const hasQuality = quality !== undefined;
    return (_jsxs("div", { className: cn('grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(0,3fr)]', className), "aria-busy": isLoading, children: [_jsxs(Card, { className: "border-border/60 bg-[hsl(var(--surface-elevated))] shadow-sm", children: [_jsx(CardHeader, { className: "space-y-2", children: _jsxs("div", { className: "flex items-start justify-between gap-2", children: [_jsxs("div", { className: "space-y-1", children: [_jsx(CardTitle, { className: "text-lg font-semibold text-foreground", children: "Evaluation snapshot" }), _jsx(CardDescription, { className: "text-sm text-muted-foreground/80", children: "Live metrics from the latest prompt release." })] }), onRefresh && !isLoading && (_jsx(Button, { variant: "ghost", size: "sm", onClick: onRefresh, "aria-label": "Refresh evaluation metrics", children: _jsx("svg", { className: "h-4 w-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", "aria-hidden": "true", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" }) }) }))] }) }), _jsx(CardContent, { children: _jsx("div", { className: "grid gap-4 sm:grid-cols-2", role: "region", "aria-label": "Evaluation metrics", "aria-live": "polite", children: isLoading ? (_jsxs(_Fragment, { children: [_jsx(MetricSkeleton, {}), _jsx(MetricSkeleton, {}), _jsx(MetricSkeleton, {}), _jsx(MetricSkeleton, {})] })) : hasMetrics ? (metrics.map((metric) => (_jsxs("div", { className: "rounded-2xl border border-border/40 bg-[hsl(var(--surface-muted))] p-4", children: [_jsx("p", { className: "text-xs font-semibold uppercase tracking-wide text-muted-foreground/70", children: metric.label }), _jsxs("div", { className: "mt-1 flex items-baseline gap-2", children: [_jsx("span", { className: "text-2xl font-semibold text-foreground", children: metric.value }), metric.trend && metric.change && (_jsxs(Badge, { variant: metric.trend === 'down'
                                                    ? 'destructive'
                                                    : metric.trend === 'up'
                                                        ? 'success'
                                                        : 'info', children: [trendCopy[metric.trend], " ", metric.change] }))] })] }, metric.id)))) : (_jsx("div", { className: "col-span-full", children: _jsx(EmptyState, { message: emptyMessage, onRefresh: onRefresh }) })) }) })] }), _jsxs("div", { className: "space-y-6", children: [(isLoading || hasQuality) && (_jsx("div", { "aria-live": "polite", children: isLoading ? (_jsxs(Card, { className: "border-border/60 bg-[hsl(var(--surface-elevated))] shadow-sm", children: [_jsxs(CardHeader, { className: "space-y-2", children: [_jsx(Skeleton, { width: "50%", height: 20 }), _jsx(Skeleton, { width: "80%", height: 14 })] }), _jsxs(CardContent, { className: "space-y-4", children: [_jsx(Skeleton, { width: "100%", height: 48 }), _jsx(Skeleton, { width: "100%", height: 64 }), _jsx(Skeleton, { width: "100%", height: 64 })] })] })) : (quality && (_jsx(ResponseQualityMeter, { ...quality, className: "border-border/60 bg-[hsl(var(--surface-elevated))] shadow-sm" }))) })), (isLoading || hasSparklines) && (_jsxs(Card, { className: "border-border/60 bg-[hsl(var(--surface-elevated))] shadow-sm", children: [_jsxs(CardHeader, { className: "space-y-2", children: [_jsx(CardTitle, { className: "text-lg font-semibold text-foreground", children: "Cost & latency trends" }), _jsx(CardDescription, { className: "text-sm text-muted-foreground/80", children: "Track performance indicators against team objectives." })] }), _jsx(CardContent, { className: "space-y-4", role: "region", "aria-label": "Performance trends", children: isLoading ? (_jsxs(_Fragment, { children: [_jsx(SparklineSkeleton, {}), _jsx(SparklineSkeleton, {}), _jsx(SparklineSkeleton, {})] })) : (sparklines.map((sparkline) => {
                                    const isOverObjective = sparkline.objective !== undefined &&
                                        sparkline.percentage > sparkline.objective;
                                    const isNearObjective = sparkline.objective !== undefined &&
                                        sparkline.percentage >= sparkline.objective * 0.9 &&
                                        sparkline.percentage <= sparkline.objective;
                                    return (_jsxs("div", { children: [_jsxs("div", { className: "flex items-center justify-between text-xs text-muted-foreground/70", children: [_jsx("span", { id: `sparkline-label-${sparkline.id}`, children: sparkline.label }), _jsxs("span", { "aria-hidden": "true", children: [Math.round(sparkline.percentage), "%"] })] }), _jsx("div", { role: "progressbar", "aria-labelledby": `sparkline-label-${sparkline.id}`, "aria-valuemin": 0, "aria-valuemax": 100, "aria-valuenow": Math.round(sparkline.percentage), "aria-valuetext": `${Math.round(sparkline.percentage)}% ${sparkline.objective !== undefined ? `of ${sparkline.objective}% target` : ''}`, className: "mt-2 h-2 w-full overflow-hidden rounded-full bg-background", children: _jsx("div", { className: cn('h-full rounded-full transition-all duration-300', isOverObjective
                                                        ? 'bg-success'
                                                        : isNearObjective
                                                            ? 'bg-warning'
                                                            : 'bg-primary'), style: {
                                                        width: `${Math.min(100, Math.max(0, sparkline.percentage))}%`,
                                                    } }) }), sparkline.objective !== undefined && (_jsxs("div", { className: "mt-1 flex items-center gap-2 text-xs text-muted-foreground/60", children: [_jsxs("span", { children: ["Target ", sparkline.objective, "%"] }), isOverObjective && (_jsx(Badge, { variant: "success", className: "text-[10px]", children: "Achieved" })), isNearObjective && (_jsx(Badge, { variant: "warning", className: "text-[10px]", children: "Almost there" }))] }))] }, sparkline.id));
                                })) })] }))] })] }));
};
EvaluationDashboard.displayName = 'EvaluationDashboard';
//# sourceMappingURL=EvaluationDashboard.js.map