import React from 'react'
import { Metadata } from 'next'
import { ApiTable } from '@/components/Demo/ApiTable'
import { CodePlayground } from '@/components/Playground/CodePlayground'
import { Callout } from '@/components/MDX/Callout'

export const metadata: Metadata = {
  title: 'Session Summary Card - Clarity Chat Components',
  description:
    'Display AI-generated conversation summaries with key highlights, metrics, and next actions.',
}

export default function SessionSummaryCardPage() {
  return (
    <div className="docs-content">
      <div className="docs-header">
        <span className="docs-badge">Component</span>
        <h1>Session Summary Card</h1>
        <p className="docs-lead">
          Show a TL;DR of your conversation. Like Cliff Notes for your chat -
          highlights what was discussed, decisions made, and what to do next.
        </p>
      </div>

      <section className="docs-section">
        <h2>Overview</h2>
        <p>
          After a long conversation, this component shows an AI-generated
          summary. Perfect for team handoffs, meeting recaps, or helping users
          remember what they discussed.
        </p>

        <Callout type="info" title="When Is This Useful?">
          Long conversations are hard to remember. Summaries help users quickly
          recall what happened and what they should do next. Think "meeting
          minutes" but automated.
        </Callout>
      </section>

      <section className="docs-section">
        <h2>Basic Usage</h2>
        <CodePlayground
          initialCode={`function SimpleSummary() {
  const summary = {
    title: 'Conversation Summary',
    highlights: [
      'Discussed implementation of new chat feature',
      'Reviewed technical requirements and constraints',
      'Identified need for streaming support'
    ],
    nextActions: [
      'Set up streaming infrastructure',
      'Create proof of concept',
      'Schedule follow-up review'
    ]
  }

  const metrics = [
    { label: 'Duration', value: '23 min' },
    { label: 'Messages', value: '47' },
    { label: 'Topics', value: '3' }
  ]

  return (
    <SessionSummaryCard
      summary={summary}
      metrics={metrics}
    />
  )
}

render(<SimpleSummary />)`}
        />
      </section>

      <section className="docs-section">
        <h2>With Metrics and Trends</h2>
        <CodePlayground
          initialCode={`function TrendingSummary() {
  const summary = {
    title: 'Support Session Recap',
    highlights: [
      'Customer reported login issues',
      'Identified root cause: expired OAuth token',
      'Provided solution and verified fix'
    ],
    nextActions: [
      'Monitor for similar issues',
      'Update documentation',
      'Schedule follow-up with customer'
    ]
  }

  const metrics = [
    { label: 'Resolution Time', value: '12 min', trend: 'down' },
    { label: 'Customer Satisfaction', value: '5/5', trend: 'steady' },
    { label: 'Issues Resolved', value: '3', trend: 'up' }
  ]

  return (
    <SessionSummaryCard
      summary={summary}
      metrics={metrics}
      title="Support Ticket Summary"
      subtitle="Generated by AI from conversation transcript"
      onExport={() => logger.debug('Export clicked')}
    />
  )
}

render(<TrendingSummary />)`}
        />
      </section>

      <section className="docs-section">
        <h2>Props</h2>
        <ApiTable title="SessionSummaryCard Props" data={summaryProps} />
      </section>

      <section className="docs-section">
        <h2>Generating Summaries with AI</h2>
        <pre>
          <code>{`// Generate summary using OpenAI
async function generateSummary(messages: Message[]) {
  const response = await openai.chat.completions.create({
    model: 'gpt-4',
    messages: [
      {
        role: 'system',
        content: \`Summarize this conversation. Return JSON:
        {
          highlights: string[] (3-5 key points),
          nextActions: string[] (2-4 suggested next steps)
        }\`
      },
      ...messages
    ],
    response_format: { type: 'json_object' }
  })

  return JSON.parse(response.choices[0].message.content)
}

// Use in component
const [summary, setSummary] = useState(null)

useEffect(() => {
  if (messages.length > 5) {
    generateSummary(messages).then(setSummary)
  }
}, [messages])`}</code>
        </pre>
      </section>

      <section className="docs-section">
        <h2>Best Practices</h2>
        <ul>
          <li>Generate summaries for conversations longer than 10 messages</li>
          <li>Keep highlights to 3-5 most important points</li>
          <li>Make next actions specific and actionable</li>
          <li>Include relevant metrics (time, messages, topics)</li>
          <li>Offer export functionality for sharing</li>
        </ul>
      </section>

      <section className="docs-section">
        <h2>Related</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <a
            href="/reference/components/conversation-timeline"
            className="docs-card"
          >
            <h3>Conversation Timeline</h3>
            <p>Detailed event timeline</p>
          </a>
          <a href="/reference/components/export-dialog" className="docs-card">
            <h3>Export Dialog</h3>
            <p>Export conversation data</p>
          </a>
        </div>
      </section>
    </div>
  )
}

const summaryProps = [
  {
    name: 'summary',
    type: 'SessionSummaryHighlights',
    required: true,
    description: 'Summary with highlights and next actions',
  },
  {
    name: 'metrics',
    type: 'SessionMetric[]',
    required: true,
    description: 'Conversation metrics to display',
  },
  {
    name: 'onAction',
    type: '(action: string) => void',
    required: false,
    description: 'Callback when next action is clicked',
  },
  {
    name: 'onExport',
    type: '() => void',
    required: false,
    description: 'Callback to export summary',
  },
  {
    name: 'title',
    type: 'string',
    required: false,
    description: 'Section heading',
  },
  {
    name: 'subtitle',
    type: 'string',
    required: false,
    description: 'Description text',
  },
  {
    name: 'className',
    type: 'string',
    required: false,
    description: 'Additional CSS classes',
  },
]
