/**
 * Knowledge Base type definitions
 */

export interface MessageReference {
  messageId: string
  chatId: string
  excerpt: string
  timestamp: Date
}

export interface KnowledgeSection {
  id: string
  title: string
  content: string
  sources: MessageReference[]
  confidence: number
  tags: string[]
  createdAt: Date
  updatedAt: Date
}

export interface KnowledgeBase {
  id: string
  projectId: string
  sections: KnowledgeSection[]
  autoGenerated: boolean
  lastUpdated: Date
  version: number
}

export interface KnowledgeBaseExportOptions {
  format: 'pdf' | 'docx' | 'markdown'
  includeSources: boolean
  includeMetadata: boolean
  customTemplate?: string
}

export interface KnowledgeBaseUpdate {
  sectionId?: string
  action: 'add' | 'update' | 'delete' | 'merge'
  data: Partial<KnowledgeSection>
}
