/**
 * Knowledge Base type definitions
 *
 * This module contains types for the auto-generated knowledge base
 * feature, which extracts and organizes information from conversations.
 *
 * @packageDocumentation
 */

/**
 * Reference to a source message in a conversation.
 *
 * @remarks
 * Used to track where knowledge was extracted from,
 * providing traceability and citation support.
 *
 * @example
 * ```typescript
 * const reference: MessageReference = {
 *   messageId: 'msg-123',
 *   chatId: 'chat-456',
 *   excerpt: 'The API uses JWT tokens for authentication...',
 *   timestamp: new Date(),
 * }
 * ```
 */
export interface MessageReference {
  /** ID of the source message */
  messageId: string
  /** ID of the chat containing the message */
  chatId: string
  /** Relevant excerpt from the message */
  excerpt: string
  /** When the message was created */
  timestamp: Date
}

/**
 * A section of organized knowledge.
 *
 * @remarks
 * Sections represent coherent topics or subjects extracted
 * from conversations, with source references for verification.
 *
 * @example
 * ```typescript
 * const section: KnowledgeSection = {
 *   id: 'section-1',
 *   title: 'Authentication Architecture',
 *   content: 'The system uses JWT tokens with refresh token rotation...',
 *   sources: [
 *     { messageId: 'msg-1', chatId: 'chat-1', excerpt: '...', timestamp: new Date() },
 *   ],
 *   confidence: 0.92,
 *   tags: ['authentication', 'security', 'jwt'],
 *   createdAt: new Date(),
 *   updatedAt: new Date(),
 * }
 * ```
 */
export interface KnowledgeSection {
  /** Unique section identifier */
  id: string
  /** Section title */
  title: string
  /** Section content (may be markdown) */
  content: string
  /** References to source messages */
  sources: MessageReference[]
  /** Confidence score (0-1) in accuracy */
  confidence: number
  /** Tags for categorization */
  tags: string[]
  /** When the section was created */
  createdAt: Date
  /** When the section was last updated */
  updatedAt: Date
}

/**
 * A project's knowledge base.
 *
 * @remarks
 * Knowledge bases are automatically generated from project conversations
 * and can be manually edited or exported.
 *
 * @example
 * ```typescript
 * const kb: KnowledgeBase = {
 *   id: 'kb-1',
 *   projectId: 'proj-1',
 *   sections: [
 *     { id: 'section-1', title: 'Overview', ... },
 *   ],
 *   autoGenerated: true,
 *   lastUpdated: new Date(),
 *   version: 3,
 * }
 * ```
 */
export interface KnowledgeBase {
  /** Unique knowledge base identifier */
  id: string
  /** ID of the project this belongs to */
  projectId: string
  /** Knowledge sections */
  sections: KnowledgeSection[]
  /** Whether this was auto-generated (vs manually created) */
  autoGenerated: boolean
  /** When the knowledge base was last updated */
  lastUpdated: Date
  /** Version number (incremented on updates) */
  version: number
}

/**
 * Options for exporting a knowledge base.
 *
 * @example
 * ```typescript
 * const options: KnowledgeBaseExportOptions = {
 *   format: 'markdown',
 *   includeSources: true,
 *   includeMetadata: false,
 *   customTemplate: '# {{title}}\n\n{{content}}',
 * }
 * ```
 */
export interface KnowledgeBaseExportOptions {
  /** Export format */
  format: 'pdf' | 'docx' | 'markdown'
  /** Include source references in export */
  includeSources: boolean
  /** Include metadata (confidence, timestamps, etc.) */
  includeMetadata: boolean
  /** Custom template for formatting (format-specific) */
  customTemplate?: string
}

/**
 * Update operation for a knowledge base.
 *
 * @remarks
 * Represents a single update action on the knowledge base,
 * supporting add, update, delete, and merge operations.
 *
 * @example
 * ```typescript
 * const update: KnowledgeBaseUpdate = {
 *   sectionId: 'section-1',
 *   action: 'update',
 *   data: {
 *     title: 'Updated Title',
 *     content: 'Updated content...',
 *   },
 * }
 * ```
 */
export interface KnowledgeBaseUpdate {
  /** ID of section to update (required for update/delete/merge) */
  sectionId?: string
  /** Action to perform */
  action: 'add' | 'update' | 'delete' | 'merge'
  /** Data for the operation */
  data: Partial<KnowledgeSection>
}
