/**
 * Conversation Export
 *
 * Utilities for exporting chat conversations to various formats.
 * Supports markdown and JSON export with proper formatting.
 */

// Re-export copyToClipboard from local demos utils
export { copyToClipboard } from '@/lib/demos/utils'

export interface ExportMessage {
  role: 'user' | 'assistant' | 'system'
  content: string
  timestamp?: string
  sources?: Array<{ url: string; title: string; score?: number }>
}

export interface ExportMetadata {
  sessionId?: string
  userId?: string
  exportedAt: string
  messageCount: number
  model?: string
  title?: string
}

export interface ConversationExport {
  metadata: ExportMetadata
  messages: ExportMessage[]
}

/**
 * Export conversation as markdown
 */
export function exportAsMarkdown(
  messages: ExportMessage[],
  metadata?: Partial<ExportMetadata>
): string {
  const lines: string[] = []

  // Header
  lines.push('# Chat Conversation')
  lines.push('')

  if (metadata?.title) {
    lines.push(`**Title:** ${metadata.title}`)
    lines.push('')
  }

  // Metadata section
  lines.push('## Metadata')
  lines.push('')
  lines.push(`- **Exported:** ${metadata?.exportedAt || new Date().toISOString()}`)
  lines.push(`- **Messages:** ${messages.length}`)

  if (metadata?.sessionId) {
    lines.push(`- **Session ID:** ${metadata.sessionId}`)
  }

  if (metadata?.model) {
    lines.push(`- **Model:** ${metadata.model}`)
  }

  lines.push('')
  lines.push('---')
  lines.push('')

  // Messages section
  lines.push('## Conversation')
  lines.push('')

  for (const message of messages) {
    // Skip system messages in markdown export
    if (message.role === 'system') continue

    // Timestamp
    if (message.timestamp) {
      const date = new Date(message.timestamp)
      lines.push(`_${date.toLocaleString()}_`)
      lines.push('')
    }

    // Role indicator
    const roleLabel = message.role === 'user' ? '👤 User' : '🤖 Assistant'
    lines.push(`### ${roleLabel}`)
    lines.push('')

    // Message content
    lines.push(message.content)
    lines.push('')

    // Sources (if any)
    if (message.sources && message.sources.length > 0) {
      lines.push('**Sources:**')
      lines.push('')

      for (const source of message.sources) {
        const scoreText = source.score ? ` (${(source.score * 100).toFixed(0)}% relevance)` : ''
        lines.push(`- [${source.title}](${source.url})${scoreText}`)
      }

      lines.push('')
    }

    lines.push('---')
    lines.push('')
  }

  // Footer
  lines.push('_Generated by Clarity Chat Documentation Assistant_')
  lines.push('')

  return lines.join('\n')
}

/**
 * Export conversation as JSON
 */
export function exportAsJSON(
  messages: ExportMessage[],
  metadata?: Partial<ExportMetadata>
): string {
  const exportData: ConversationExport = {
    metadata: {
      exportedAt: metadata?.exportedAt || new Date().toISOString(),
      messageCount: messages.length,
      sessionId: metadata?.sessionId,
      userId: metadata?.userId,
      model: metadata?.model,
      title: metadata?.title,
    },
    messages: messages.map(msg => ({
      role: msg.role,
      content: msg.content,
      timestamp: msg.timestamp,
      sources: msg.sources,
    })),
  }

  return JSON.stringify(exportData, null, 2)
}

/**
 * Export conversation as plain text
 */
export function exportAsText(
  messages: ExportMessage[],
  metadata?: Partial<ExportMetadata>
): string {
  const lines: string[] = []

  // Header
  lines.push('CHAT CONVERSATION')
  lines.push('='.repeat(80))
  lines.push('')

  if (metadata?.title) {
    lines.push(`Title: ${metadata.title}`)
    lines.push('')
  }

  lines.push(`Exported: ${metadata?.exportedAt || new Date().toISOString()}`)
  lines.push(`Messages: ${messages.length}`)

  if (metadata?.sessionId) {
    lines.push(`Session ID: ${metadata.sessionId}`)
  }

  if (metadata?.model) {
    lines.push(`Model: ${metadata.model}`)
  }

  lines.push('')
  lines.push('='.repeat(80))
  lines.push('')

  // Messages
  for (const message of messages) {
    // Skip system messages in text export
    if (message.role === 'system') continue

    // Timestamp
    if (message.timestamp) {
      const date = new Date(message.timestamp)
      lines.push(`[${date.toLocaleString()}]`)
    }

    // Role
    const roleLabel = message.role === 'user' ? 'USER' : 'ASSISTANT'
    lines.push(`${roleLabel}:`)

    // Content
    lines.push(message.content)

    // Sources
    if (message.sources && message.sources.length > 0) {
      lines.push('')
      lines.push('Sources:')
      for (const source of message.sources) {
        const scoreText = source.score ? ` (${(source.score * 100).toFixed(0)}%)` : ''
        lines.push(`  - ${source.title}${scoreText}`)
        lines.push(`    ${source.url}`)
      }
    }

    lines.push('')
    lines.push('-'.repeat(80))
    lines.push('')
  }

  // Footer
  lines.push('Generated by Clarity Chat Documentation Assistant')
  lines.push('')

  return lines.join('\n')
}

/**
 * Download conversation as a file
 */
export function downloadConversation(
  content: string,
  format: 'markdown' | 'json' | 'text',
  filename?: string
): void {
  // Determine file extension and MIME type
  const extensions = {
    markdown: '.md',
    json: '.json',
    text: '.txt',
  }

  const mimeTypes = {
    markdown: 'text/markdown',
    json: 'application/json',
    text: 'text/plain',
  }

  const extension = extensions[format]
  const mimeType = mimeTypes[format]

  // Generate filename if not provided
  const defaultFilename = `conversation_${new Date().toISOString().split('T')[0]}${extension}`
  const finalFilename = filename || defaultFilename

  // Create blob and download
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)

  const link = document.createElement('a')
  link.href = url
  link.download = finalFilename
  document.body.appendChild(link)
  link.click()

  // Cleanup
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

// copyToClipboard is re-exported from @/lib/demos/utils

/**
 * Get export statistics
 */
export function getExportStats(messages: ExportMessage[]): {
  totalMessages: number
  userMessages: number
  assistantMessages: number
  totalCharacters: number
  estimatedTokens: number
  sourcesCount: number
  hasTimestamps: boolean
} {
  const userMessages = messages.filter(m => m.role === 'user').length
  const assistantMessages = messages.filter(m => m.role === 'assistant').length
  const totalCharacters = messages.reduce((sum, m) => sum + m.content.length, 0)

  // Rough token estimation (1 token ≈ 4 characters)
  const estimatedTokens = Math.ceil(totalCharacters / 4)

  // Count total sources
  const sourcesCount = messages.reduce(
    (sum, m) => sum + (m.sources?.length || 0),
    0
  )

  // Check if messages have timestamps
  const hasTimestamps = messages.some(m => !!m.timestamp)

  return {
    totalMessages: messages.length,
    userMessages,
    assistantMessages,
    totalCharacters,
    estimatedTokens,
    sourcesCount,
    hasTimestamps,
  }
}
