import type { Metadata, Viewport } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: {
    default: 'Clarity Chat - Premium React Components for AI Chat',
    template: '%s | Clarity Chat',
  },
  description:
    'Production-ready React components for AI chat. Multi-provider support (OpenAI, Anthropic, Gemini), intelligent memory, 40%+ token cost savings. Ship in days, not months.',
  keywords: [
    'AI chat',
    'React components',
    'OpenAI',
    'Anthropic',
    'Claude',
    'Gemini',
    'chat UI',
    'streaming',
    'token optimization',
    'TypeScript',
  ],
  authors: [{ name: 'Code & Clarity' }],
  creator: 'Code & Clarity',
  publisher: 'Code & Clarity',
  metadataBase: new URL('https://clarity-chat.dev'),
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://clarity-chat.dev',
    siteName: 'Clarity Chat',
    title: 'Clarity Chat - Build AI Chat Faster Than Ever',
    description:
      'Production-ready React components for AI chat. Multi-provider support, intelligent memory, 40%+ cost savings.',
    // Images are auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Clarity Chat - Build AI Chat Faster Than Ever',
    description:
      'Production-ready React components for AI chat. Multi-provider support, intelligent memory, 40%+ cost savings.',
    creator: '@claritychat',
    // Images are auto-generated by twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  // Icons are auto-generated by icon.tsx and apple-icon.tsx
  manifest: '/site.webmanifest',
}

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#0a0a0a' },
    { media: '(prefers-color-scheme: dark)', color: '#0a0a0a' },
  ],
  width: 'device-width',
  initialScale: 1,
}

import MarketingAssistant from '@/components/marketing-assistant/ChatWidget'
import SmoothScroll from '@/components/ui/SmoothScroll'
import ScrollProgress from '@/components/ui/ScrollProgress'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className="min-h-screen bg-surface-950 text-white antialiased font-sans">
        <SmoothScroll>
          <ScrollProgress />
          {children}
          <MarketingAssistant />
        </SmoothScroll>
      </body>
    </html>
  )
}
