import type { ComponentDefinition } from '../types'

export const componentDefinitions: ComponentDefinition[] = [
  {
    id: 'ChatInput',
    name: 'Chat Input',
    category: 'Core',
    description: 'Multi-line chat input with voice, attachments, and mentions',
    importPath: '@clarity-chat/react',
    props: [
      {
        name: 'placeholder',
        type: 'string',
        default: 'Type a message...',
        description: 'Placeholder text for the input',
      },
      {
        name: 'disabled',
        type: 'boolean',
        default: false,
        description: 'Disable the input',
      },
      {
        name: 'maxLength',
        type: 'number',
        default: 4000,
        description: 'Maximum character count',
        min: 100,
        max: 10000,
        step: 100,
      },
      {
        name: 'variant',
        type: 'select',
        default: 'default',
        description: 'Visual variant',
        options: [
          { label: 'Default', value: 'default' },
          { label: 'Minimal', value: 'minimal' },
          { label: 'Compact', value: 'compact' },
        ],
      },
      {
        name: 'enableVoice',
        type: 'boolean',
        default: true,
        description: 'Show voice input button',
      },
      {
        name: 'enableAttachments',
        type: 'boolean',
        default: true,
        description: 'Show attachment button',
      },
      {
        name: 'enableMentions',
        type: 'boolean',
        default: false,
        description: 'Enable @ mentions',
      },
      {
        name: 'rows',
        type: 'number',
        default: 3,
        description: 'Number of visible rows',
        min: 1,
        max: 10,
        step: 1,
      },
    ],
    examples: [
      {
        name: 'Minimal',
        description: 'Simple input without extra features',
        props: {
          variant: 'minimal',
          enableVoice: false,
          enableAttachments: false,
          rows: 1,
        },
      },
      {
        name: 'Full Featured',
        description: 'All features enabled',
        props: {
          enableVoice: true,
          enableAttachments: true,
          enableMentions: true,
          maxLength: 8000,
        },
      },
    ],
  },
  {
    id: 'MessageBubble',
    name: 'Message Bubble',
    category: 'Messages',
    description: 'Chat message bubble with avatar and metadata',
    importPath: '@clarity-chat/react',
    props: [
      {
        name: 'content',
        type: 'string',
        default: 'Hello! How can I help you today?',
        description: 'Message content',
      },
      {
        name: 'role',
        type: 'select',
        default: 'assistant',
        description: 'Message sender role',
        options: [
          { label: 'Assistant', value: 'assistant' },
          { label: 'User', value: 'user' },
          { label: 'System', value: 'system' },
        ],
      },
      {
        name: 'variant',
        type: 'select',
        default: 'default',
        description: 'Visual style',
        options: [
          { label: 'Default', value: 'default' },
          { label: 'Compact', value: 'compact' },
          { label: 'Minimal', value: 'minimal' },
        ],
      },
      {
        name: 'showAvatar',
        type: 'boolean',
        default: true,
        description: 'Display avatar',
      },
      {
        name: 'showTimestamp',
        type: 'boolean',
        default: true,
        description: 'Display timestamp',
      },
      {
        name: 'isStreaming',
        type: 'boolean',
        default: false,
        description: 'Show streaming indicator',
      },
      {
        name: 'enableActions',
        type: 'boolean',
        default: true,
        description: 'Show action buttons (copy, like, etc)',
      },
    ],
  },
  {
    id: 'ThinkingIndicator',
    name: 'Thinking Indicator',
    category: 'AI Reasoning',
    description: 'Animated thinking/processing indicator',
    importPath: '@clarity-chat/react',
    props: [
      {
        name: 'message',
        type: 'string',
        default: 'Thinking...',
        description: 'Status message',
      },
      {
        name: 'variant',
        type: 'select',
        default: 'dots',
        description: 'Animation style',
        options: [
          { label: 'Dots', value: 'dots' },
          { label: 'Pulse', value: 'pulse' },
          { label: 'Wave', value: 'wave' },
          { label: 'Spinner', value: 'spinner' },
        ],
      },
      {
        name: 'size',
        type: 'select',
        default: 'md',
        description: 'Size variant',
        options: [
          { label: 'Small', value: 'sm' },
          { label: 'Medium', value: 'md' },
          { label: 'Large', value: 'lg' },
        ],
      },
      {
        name: 'showProgress',
        type: 'boolean',
        default: false,
        description: 'Show progress indicator',
      },
    ],
  },
  {
    id: 'TokenCounter',
    name: 'Token Counter',
    category: 'Token Management',
    description: 'Real-time token counting display',
    importPath: '@clarity-chat/token-optimization',
    props: [
      {
        name: 'currentTokens',
        type: 'number',
        default: 1234,
        description: 'Current token count',
        min: 0,
        max: 100000,
        step: 1,
      },
      {
        name: 'maxTokens',
        type: 'number',
        default: 4000,
        description: 'Maximum tokens',
        min: 1000,
        max: 100000,
        step: 1000,
      },
      {
        name: 'variant',
        type: 'select',
        default: 'default',
        description: 'Display style',
        options: [
          { label: 'Default', value: 'default' },
          { label: 'Compact', value: 'compact' },
          { label: 'Badge', value: 'badge' },
        ],
      },
      {
        name: 'showWarning',
        type: 'boolean',
        default: true,
        description: 'Show warning when approaching limit',
      },
      {
        name: 'warningThreshold',
        type: 'number',
        default: 0.8,
        description: 'Warning threshold (0-1)',
        min: 0.5,
        max: 1,
        step: 0.1,
      },
    ],
  },
  {
    id: 'CommandPalette',
    name: 'Command Palette',
    category: 'Navigation',
    description: 'Keyboard-driven command interface',
    importPath: '@clarity-chat/react',
    props: [
      {
        name: 'placeholder',
        type: 'string',
        default: 'Type a command...',
        description: 'Search placeholder',
      },
      {
        name: 'shortcuts',
        type: 'boolean',
        default: true,
        description: 'Show keyboard shortcuts',
      },
      {
        name: 'recentCommands',
        type: 'boolean',
        default: true,
        description: 'Show recent commands',
      },
      {
        name: 'groupCommands',
        type: 'boolean',
        default: true,
        description: 'Group commands by category',
      },
      {
        name: 'maxHeight',
        type: 'number',
        default: 400,
        description: 'Maximum height in pixels',
        min: 200,
        max: 800,
        step: 50,
      },
    ],
  },
  {
    id: 'AudioRecorder',
    name: 'Audio Recorder',
    category: 'Input',
    description: 'Voice recording with waveform visualization',
    importPath: '@clarity-chat/react',
    props: [
      {
        name: 'maxDuration',
        type: 'number',
        default: 60,
        description: 'Max recording duration (seconds)',
        min: 10,
        max: 300,
        step: 10,
      },
      {
        name: 'visualizer',
        type: 'select',
        default: 'waveform',
        description: 'Visualization type',
        options: [
          { label: 'Waveform', value: 'waveform' },
          { label: 'Bars', value: 'bars' },
          { label: 'Circle', value: 'circle' },
          { label: 'None', value: 'none' },
        ],
      },
      {
        name: 'showTimer',
        type: 'boolean',
        default: true,
        description: 'Show recording timer',
      },
      {
        name: 'showTranscript',
        type: 'boolean',
        default: true,
        description: 'Show live transcript',
      },
      {
        name: 'autoStop',
        type: 'boolean',
        default: true,
        description: 'Auto-stop at max duration',
      },
    ],
  },
  {
    id: 'ToolCard',
    name: 'Tool Card',
    category: 'Tools',
    description: 'Display for tool execution and results',
    importPath: '@clarity-chat/react',
    props: [
      {
        name: 'toolName',
        type: 'string',
        default: 'search_web',
        description: 'Tool identifier',
      },
      {
        name: 'status',
        type: 'select',
        default: 'success',
        description: 'Execution status',
        options: [
          { label: 'Pending', value: 'pending' },
          { label: 'Running', value: 'running' },
          { label: 'Success', value: 'success' },
          { label: 'Error', value: 'error' },
        ],
      },
      {
        name: 'collapsible',
        type: 'boolean',
        default: true,
        description: 'Allow collapsing',
      },
      {
        name: 'showIcon',
        type: 'boolean',
        default: true,
        description: 'Show tool icon',
      },
      {
        name: 'showDuration',
        type: 'boolean',
        default: true,
        description: 'Show execution time',
      },
    ],
  },
  {
    id: 'CodeBlock',
    name: 'Code Block',
    category: 'Code & Data',
    description: 'Syntax-highlighted code with copy button',
    importPath: '@clarity-chat/react',
    props: [
      {
        name: 'language',
        type: 'select',
        default: 'typescript',
        description: 'Programming language',
        options: [
          { label: 'TypeScript', value: 'typescript' },
          { label: 'JavaScript', value: 'javascript' },
          { label: 'Python', value: 'python' },
          { label: 'JSON', value: 'json' },
          { label: 'CSS', value: 'css' },
          { label: 'HTML', value: 'html' },
        ],
      },
      {
        name: 'theme',
        type: 'select',
        default: 'github-dark',
        description: 'Syntax theme',
        options: [
          { label: 'GitHub Dark', value: 'github-dark' },
          { label: 'GitHub Light', value: 'github-light' },
          { label: 'VS Code Dark', value: 'vscode-dark' },
          { label: 'Dracula', value: 'dracula' },
        ],
      },
      {
        name: 'showLineNumbers',
        type: 'boolean',
        default: true,
        description: 'Display line numbers',
      },
      {
        name: 'showCopyButton',
        type: 'boolean',
        default: true,
        description: 'Show copy button',
      },
      {
        name: 'wrapLines',
        type: 'boolean',
        default: false,
        description: 'Wrap long lines',
      },
    ],
  },
]
