import type { Meta, StoryObj } from '@storybook/react-vite';
import { Drawer } from '@clarity-chat/primitives';
declare const meta: Meta<typeof Drawer>;
export default meta;
type Story = StoryObj<typeof Drawer>;
export declare const RightSide: Story;
export declare const LeftSide: Story;
export declare const TopSide: Story;
export declare const BottomSide: Story;
export declare const SmallSize: Story;
export declare const MediumSize: Story;
export declare const LargeSize: Story;
export declare const ExtraLargeSize: Story;
export declare const FullSize: Story;
export declare const NavigationDrawer: Story;
export declare const SettingsDrawer: Story;
export declare const FilterDrawer: Story;
export declare const NotificationDrawer: Story;
export declare const MobileSheet: Story;
export declare const NoBackdropBlur: Story;
export declare const NoClickOutsideClose: Story;
export declare const ControlledDrawer: Story;
//# sourceMappingURL=Drawer.stories.d.ts.map